// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID           pgtype.UUID        `json:"id"`
	ActorID      string             `json:"actor_id"`
	Action       string             `json:"action"`
	ResourceType string             `json:"resource_type"`
	ResourceID   string             `json:"resource_id"`
	Details      []byte             `json:"details"`
	IpAddress    pgtype.Text        `json:"ip_address"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Campaign struct {
	ID                  pgtype.UUID        `json:"id"`
	OwnerID             string             `json:"owner_id"`
	Title               string             `json:"title"`
	Description         pgtype.Text        `json:"description"`
	BriefUrl            pgtype.Text        `json:"brief_url"`
	Platform            string             `json:"platform"`
	Status              string             `json:"status"`
	CpmRate             int32              `json:"cpm_rate"`
	TotalBudget         int32              `json:"total_budget"`
	RemainingBudget     int32              `json:"remaining_budget"`
	PlatformFee         int32              `json:"platform_fee"`
	EscrowID            pgtype.Text        `json:"escrow_id"`
	MaxClipsPerCampaign pgtype.Int4        `json:"max_clips_per_campaign"`
	MaxClipsPerClipper  pgtype.Int4        `json:"max_clips_per_clipper"`
	MinViewsPerClip     pgtype.Int4        `json:"min_views_per_clip"`
	AutoApproveHours    pgtype.Int4        `json:"auto_approve_hours"`
	StartsAt            pgtype.Timestamptz `json:"starts_at"`
	EndsAt              pgtype.Timestamptz `json:"ends_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type FraudFlag struct {
	ID           pgtype.UUID        `json:"id"`
	SubmissionID pgtype.UUID        `json:"submission_id"`
	UserID       pgtype.Text        `json:"user_id"`
	FlagType     string             `json:"flag_type"`
	Severity     string             `json:"severity"`
	Description  pgtype.Text        `json:"description"`
	Status       string             `json:"status"`
	ResolvedBy   pgtype.Text        `json:"resolved_by"`
	Resolution   pgtype.Text        `json:"resolution"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	ResolvedAt   pgtype.Timestamptz `json:"resolved_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type LedgerEntry struct {
	ID             pgtype.UUID        `json:"id"`
	IdempotencyKey string             `json:"idempotency_key"`
	EntryType      string             `json:"entry_type"`
	CampaignID     pgtype.UUID        `json:"campaign_id"`
	SubmissionID   pgtype.UUID        `json:"submission_id"`
	ClipperID      pgtype.Text        `json:"clipper_id"`
	Amount         int32              `json:"amount"`
	Description    pgtype.Text        `json:"description"`
	Metadata       []byte             `json:"metadata"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type MetricSnapshot struct {
	ID           pgtype.UUID        `json:"id"`
	SubmissionID pgtype.UUID        `json:"submission_id"`
	Platform     string             `json:"platform"`
	Views        int64              `json:"views"`
	Likes        int64              `json:"likes"`
	Comments     int64              `json:"comments"`
	Shares       int64              `json:"shares"`
	CapturedAt   pgtype.Timestamptz `json:"captured_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type PayoutRequest struct {
	ID             pgtype.UUID        `json:"id"`
	ClipperID      string             `json:"clipper_id"`
	Amount         int32              `json:"amount"`
	UpiID          string             `json:"upi_id"`
	Status         string             `json:"status"`
	ProviderRef    pgtype.Text        `json:"provider_ref"`
	FailureReason  pgtype.Text        `json:"failure_reason"`
	IdempotencyKey string             `json:"idempotency_key"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ProcessedAt    pgtype.Timestamptz `json:"processed_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type SocialAccount struct {
	ID               pgtype.UUID        `json:"id"`
	UserID           string             `json:"user_id"`
	Platform         string             `json:"platform"`
	PlatformUserID   string             `json:"platform_user_id"`
	PlatformUsername pgtype.Text        `json:"platform_username"`
	AccessToken      pgtype.Text        `json:"access_token"`
	RefreshToken     pgtype.Text        `json:"refresh_token"`
	TokenExpiresAt   pgtype.Timestamptz `json:"token_expires_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type Submission struct {
	ID              pgtype.UUID        `json:"id"`
	CampaignID      pgtype.UUID        `json:"campaign_id"`
	ClipperID       string             `json:"clipper_id"`
	PostUrl         string             `json:"post_url"`
	Platform        string             `json:"platform"`
	PlatformPostID  pgtype.Text        `json:"platform_post_id"`
	Status          string             `json:"status"`
	RejectionReason pgtype.Text        `json:"rejection_reason"`
	ApprovedAt      pgtype.Timestamptz `json:"approved_at"`
	AutoApprovedAt  pgtype.Timestamptz `json:"auto_approved_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID          string             `json:"id"`
	Email       string             `json:"email"`
	DisplayName pgtype.Text        `json:"display_name"`
	Role        string             `json:"role"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	UpiID       pgtype.Text        `json:"upi_id"`
}
