// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approveSubmission = `-- name: ApproveSubmission :execrows
UPDATE submissions
SET status = 'approved', approved_at = NOW(), updated_at = NOW()
WHERE id = $1 AND status = 'pending'
`

func (q *Queries) ApproveSubmission(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, approveSubmission, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const autoApproveSubmission = `-- name: AutoApproveSubmission :execrows
UPDATE submissions
SET status = 'auto_approved', auto_approved_at = NOW(), updated_at = NOW()
WHERE id = $1 AND status = 'pending'
`

func (q *Queries) AutoApproveSubmission(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, autoApproveSubmission, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countCampaignsFiltered = `-- name: CountCampaignsFiltered :one
SELECT COUNT(*) FROM campaigns
WHERE status IN ('active', 'funded')
  AND (ends_at IS NULL OR ends_at > NOW())
  AND ($1::text = '' OR platform = $1)
  AND ($2::int = 0 OR cpm_rate <= $2)
  AND ($3::int = 0 OR remaining_budget >= $3)
  AND ($4::text = '' OR title ILIKE '%' || $4 || '%' OR description ILIKE '%' || $4 || '%')
`

type CountCampaignsFilteredParams struct {
	Column1 string `json:"column_1"`
	Column2 int32  `json:"column_2"`
	Column3 int32  `json:"column_3"`
	Column4 string `json:"column_4"`
}

func (q *Queries) CountCampaignsFiltered(ctx context.Context, arg CountCampaignsFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCampaignsFiltered,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFraudFlagsByUser = `-- name: CountFraudFlagsByUser :one
SELECT COUNT(*)::int FROM fraud_flags WHERE user_id = $1 AND status = 'open'
`

func (q *Queries) CountFraudFlagsByUser(ctx context.Context, userID pgtype.Text) (int32, error) {
	row := q.db.QueryRow(ctx, countFraudFlagsByUser, userID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countSnapshotsBySubmission = `-- name: CountSnapshotsBySubmission :one
SELECT COUNT(*) FROM metric_snapshots
WHERE submission_id = $1
`

func (q *Queries) CountSnapshotsBySubmission(ctx context.Context, submissionID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countSnapshotsBySubmission, submissionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSubmissionsByCampaign = `-- name: CountSubmissionsByCampaign :one
SELECT COUNT(*) FROM submissions WHERE campaign_id = $1
`

func (q *Queries) CountSubmissionsByCampaign(ctx context.Context, campaignID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countSubmissionsByCampaign, campaignID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSubmissionsByClipperForCampaign = `-- name: CountSubmissionsByClipperForCampaign :one
SELECT COUNT(*) FROM submissions WHERE campaign_id = $1 AND clipper_id = $2
`

type CountSubmissionsByClipperForCampaignParams struct {
	CampaignID pgtype.UUID `json:"campaign_id"`
	ClipperID  string      `json:"clipper_id"`
}

func (q *Queries) CountSubmissionsByClipperForCampaign(ctx context.Context, arg CountSubmissionsByClipperForCampaignParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSubmissionsByClipperForCampaign, arg.CampaignID, arg.ClipperID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT COUNT(*) FROM notifications WHERE user_id = $1 AND is_read = false
`

func (q *Queries) CountUnreadNotifications(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*)::int FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createAuditLog = `-- name: CreateAuditLog :one

INSERT INTO audit_logs (actor_id, action, resource_type, resource_id, details, ip_address)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, actor_id, action, resource_type, resource_id, details, ip_address, created_at
`

type CreateAuditLogParams struct {
	ActorID      string      `json:"actor_id"`
	Action       string      `json:"action"`
	ResourceType string      `json:"resource_type"`
	ResourceID   string      `json:"resource_id"`
	Details      []byte      `json:"details"`
	IpAddress    pgtype.Text `json:"ip_address"`
}

// Audit Logs
func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.ActorID,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.Details,
		arg.IpAddress,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.ActorID,
		&i.Action,
		&i.ResourceType,
		&i.ResourceID,
		&i.Details,
		&i.IpAddress,
		&i.CreatedAt,
	)
	return i, err
}

const createCampaign = `-- name: CreateCampaign :one
INSERT INTO campaigns (
    id, owner_id, title, description, brief_url, platform, status,
    cpm_rate, total_budget, remaining_budget, platform_fee, escrow_id,
    max_clips_per_campaign, max_clips_per_clipper, min_views_per_clip,
    auto_approve_hours, starts_at, ends_at
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11, $12,
    $13, $14, $15, $16, $17, $18
)
RETURNING id, owner_id, title, description, brief_url, platform, status, cpm_rate, total_budget, remaining_budget, platform_fee, escrow_id, max_clips_per_campaign, max_clips_per_clipper, min_views_per_clip, auto_approve_hours, starts_at, ends_at, created_at, updated_at
`

type CreateCampaignParams struct {
	ID                  pgtype.UUID        `json:"id"`
	OwnerID             string             `json:"owner_id"`
	Title               string             `json:"title"`
	Description         pgtype.Text        `json:"description"`
	BriefUrl            pgtype.Text        `json:"brief_url"`
	Platform            string             `json:"platform"`
	Status              string             `json:"status"`
	CpmRate             int32              `json:"cpm_rate"`
	TotalBudget         int32              `json:"total_budget"`
	RemainingBudget     int32              `json:"remaining_budget"`
	PlatformFee         int32              `json:"platform_fee"`
	EscrowID            pgtype.Text        `json:"escrow_id"`
	MaxClipsPerCampaign pgtype.Int4        `json:"max_clips_per_campaign"`
	MaxClipsPerClipper  pgtype.Int4        `json:"max_clips_per_clipper"`
	MinViewsPerClip     pgtype.Int4        `json:"min_views_per_clip"`
	AutoApproveHours    pgtype.Int4        `json:"auto_approve_hours"`
	StartsAt            pgtype.Timestamptz `json:"starts_at"`
	EndsAt              pgtype.Timestamptz `json:"ends_at"`
}

func (q *Queries) CreateCampaign(ctx context.Context, arg CreateCampaignParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, createCampaign,
		arg.ID,
		arg.OwnerID,
		arg.Title,
		arg.Description,
		arg.BriefUrl,
		arg.Platform,
		arg.Status,
		arg.CpmRate,
		arg.TotalBudget,
		arg.RemainingBudget,
		arg.PlatformFee,
		arg.EscrowID,
		arg.MaxClipsPerCampaign,
		arg.MaxClipsPerClipper,
		arg.MinViewsPerClip,
		arg.AutoApproveHours,
		arg.StartsAt,
		arg.EndsAt,
	)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Description,
		&i.BriefUrl,
		&i.Platform,
		&i.Status,
		&i.CpmRate,
		&i.TotalBudget,
		&i.RemainingBudget,
		&i.PlatformFee,
		&i.EscrowID,
		&i.MaxClipsPerCampaign,
		&i.MaxClipsPerClipper,
		&i.MinViewsPerClip,
		&i.AutoApproveHours,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCampaignTemplate = `-- name: CreateCampaignTemplate :one
INSERT INTO campaign_templates (name, platform, cpm_rate, total_budget, max_clips_per_clipper, min_views_per_clip, auto_approve_hours, description_template)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, name, platform, cpm_rate, total_budget, max_clips_per_clipper, min_views_per_clip, auto_approve_hours, description_template, created_at
`

type CreateCampaignTemplateParams struct {
	Name                string      `json:"name"`
	Platform            string      `json:"platform"`
	CpmRate             int32       `json:"cpm_rate"`
	TotalBudget         int32       `json:"total_budget"`
	MaxClipsPerClipper  pgtype.Int4 `json:"max_clips_per_clipper"`
	MinViewsPerClip     pgtype.Int4 `json:"min_views_per_clip"`
	AutoApproveHours    pgtype.Int4 `json:"auto_approve_hours"`
	DescriptionTemplate pgtype.Text `json:"description_template"`
}

func (q *Queries) CreateCampaignTemplate(ctx context.Context, arg CreateCampaignTemplateParams) (CampaignTemplate, error) {
	row := q.db.QueryRow(ctx, createCampaignTemplate,
		arg.Name,
		arg.Platform,
		arg.CpmRate,
		arg.TotalBudget,
		arg.MaxClipsPerClipper,
		arg.MinViewsPerClip,
		arg.AutoApproveHours,
		arg.DescriptionTemplate,
	)
	var i CampaignTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Platform,
		&i.CpmRate,
		&i.TotalBudget,
		&i.MaxClipsPerClipper,
		&i.MinViewsPerClip,
		&i.AutoApproveHours,
		&i.DescriptionTemplate,
		&i.CreatedAt,
	)
	return i, err
}

const createFraudFlag = `-- name: CreateFraudFlag :one

INSERT INTO fraud_flags (submission_id, user_id, flag_type, severity, description)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, submission_id, user_id, flag_type, severity, description, status, resolved_by, resolution, created_at, resolved_at, updated_at
`

type CreateFraudFlagParams struct {
	SubmissionID pgtype.UUID `json:"submission_id"`
	UserID       pgtype.Text `json:"user_id"`
	FlagType     string      `json:"flag_type"`
	Severity     string      `json:"severity"`
	Description  pgtype.Text `json:"description"`
}

// Fraud Flags
func (q *Queries) CreateFraudFlag(ctx context.Context, arg CreateFraudFlagParams) (FraudFlag, error) {
	row := q.db.QueryRow(ctx, createFraudFlag,
		arg.SubmissionID,
		arg.UserID,
		arg.FlagType,
		arg.Severity,
		arg.Description,
	)
	var i FraudFlag
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.UserID,
		&i.FlagType,
		&i.Severity,
		&i.Description,
		&i.Status,
		&i.ResolvedBy,
		&i.Resolution,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createLedgerEntry = `-- name: CreateLedgerEntry :one
INSERT INTO ledger_entries (idempotency_key, entry_type, campaign_id, submission_id, clipper_id, amount, description, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (idempotency_key) DO NOTHING
RETURNING id, idempotency_key, entry_type, campaign_id, submission_id, clipper_id, amount, description, metadata, created_at
`

type CreateLedgerEntryParams struct {
	IdempotencyKey string      `json:"idempotency_key"`
	EntryType      string      `json:"entry_type"`
	CampaignID     pgtype.UUID `json:"campaign_id"`
	SubmissionID   pgtype.UUID `json:"submission_id"`
	ClipperID      pgtype.Text `json:"clipper_id"`
	Amount         int32       `json:"amount"`
	Description    pgtype.Text `json:"description"`
	Metadata       []byte      `json:"metadata"`
}

func (q *Queries) CreateLedgerEntry(ctx context.Context, arg CreateLedgerEntryParams) (LedgerEntry, error) {
	row := q.db.QueryRow(ctx, createLedgerEntry,
		arg.IdempotencyKey,
		arg.EntryType,
		arg.CampaignID,
		arg.SubmissionID,
		arg.ClipperID,
		arg.Amount,
		arg.Description,
		arg.Metadata,
	)
	var i LedgerEntry
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.EntryType,
		&i.CampaignID,
		&i.SubmissionID,
		&i.ClipperID,
		&i.Amount,
		&i.Description,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const createMetricSnapshot = `-- name: CreateMetricSnapshot :one
INSERT INTO metric_snapshots (submission_id, platform, views, likes, comments, shares, captured_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, submission_id, platform, views, likes, comments, shares, captured_at, created_at
`

type CreateMetricSnapshotParams struct {
	SubmissionID pgtype.UUID        `json:"submission_id"`
	Platform     string             `json:"platform"`
	Views        int64              `json:"views"`
	Likes        int64              `json:"likes"`
	Comments     int64              `json:"comments"`
	Shares       int64              `json:"shares"`
	CapturedAt   pgtype.Timestamptz `json:"captured_at"`
}

func (q *Queries) CreateMetricSnapshot(ctx context.Context, arg CreateMetricSnapshotParams) (MetricSnapshot, error) {
	row := q.db.QueryRow(ctx, createMetricSnapshot,
		arg.SubmissionID,
		arg.Platform,
		arg.Views,
		arg.Likes,
		arg.Comments,
		arg.Shares,
		arg.CapturedAt,
	)
	var i MetricSnapshot
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.Platform,
		&i.Views,
		&i.Likes,
		&i.Comments,
		&i.Shares,
		&i.CapturedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createNotification = `-- name: CreateNotification :one

INSERT INTO notifications (user_id, type, title, body, link)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, type, title, body, link, is_read, created_at
`

type CreateNotificationParams struct {
	UserID string      `json:"user_id"`
	Type   string      `json:"type"`
	Title  string      `json:"title"`
	Body   pgtype.Text `json:"body"`
	Link   pgtype.Text `json:"link"`
}

// Notification queries
func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.UserID,
		arg.Type,
		arg.Title,
		arg.Body,
		arg.Link,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.Link,
		&i.IsRead,
		&i.CreatedAt,
	)
	return i, err
}

const createPayoutRequest = `-- name: CreatePayoutRequest :one
INSERT INTO payout_requests (id, clipper_id, amount, upi_id, idempotency_key)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (idempotency_key) DO NOTHING
RETURNING id, clipper_id, amount, upi_id, status, provider_ref, failure_reason, idempotency_key, created_at, processed_at, updated_at
`

type CreatePayoutRequestParams struct {
	ID             pgtype.UUID `json:"id"`
	ClipperID      string      `json:"clipper_id"`
	Amount         int32       `json:"amount"`
	UpiID          string      `json:"upi_id"`
	IdempotencyKey string      `json:"idempotency_key"`
}

func (q *Queries) CreatePayoutRequest(ctx context.Context, arg CreatePayoutRequestParams) (PayoutRequest, error) {
	row := q.db.QueryRow(ctx, createPayoutRequest,
		arg.ID,
		arg.ClipperID,
		arg.Amount,
		arg.UpiID,
		arg.IdempotencyKey,
	)
	var i PayoutRequest
	err := row.Scan(
		&i.ID,
		&i.ClipperID,
		&i.Amount,
		&i.UpiID,
		&i.Status,
		&i.ProviderRef,
		&i.FailureReason,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.ProcessedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSocialAccount = `-- name: CreateSocialAccount :one
INSERT INTO social_accounts (user_id, platform, platform_user_id, platform_username, access_token, refresh_token, token_expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, platform, platform_user_id, platform_username, access_token, refresh_token, token_expires_at, created_at, updated_at
`

type CreateSocialAccountParams struct {
	UserID           string             `json:"user_id"`
	Platform         string             `json:"platform"`
	PlatformUserID   string             `json:"platform_user_id"`
	PlatformUsername pgtype.Text        `json:"platform_username"`
	AccessToken      pgtype.Text        `json:"access_token"`
	RefreshToken     pgtype.Text        `json:"refresh_token"`
	TokenExpiresAt   pgtype.Timestamptz `json:"token_expires_at"`
}

func (q *Queries) CreateSocialAccount(ctx context.Context, arg CreateSocialAccountParams) (SocialAccount, error) {
	row := q.db.QueryRow(ctx, createSocialAccount,
		arg.UserID,
		arg.Platform,
		arg.PlatformUserID,
		arg.PlatformUsername,
		arg.AccessToken,
		arg.RefreshToken,
		arg.TokenExpiresAt,
	)
	var i SocialAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Platform,
		&i.PlatformUserID,
		&i.PlatformUsername,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSubmission = `-- name: CreateSubmission :one
INSERT INTO submissions (id, campaign_id, clipper_id, post_url, platform, platform_post_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, campaign_id, clipper_id, post_url, platform, platform_post_id, status, rejection_reason, approved_at, auto_approved_at, created_at, updated_at
`

type CreateSubmissionParams struct {
	ID             pgtype.UUID `json:"id"`
	CampaignID     pgtype.UUID `json:"campaign_id"`
	ClipperID      string      `json:"clipper_id"`
	PostUrl        string      `json:"post_url"`
	Platform       string      `json:"platform"`
	PlatformPostID pgtype.Text `json:"platform_post_id"`
}

func (q *Queries) CreateSubmission(ctx context.Context, arg CreateSubmissionParams) (Submission, error) {
	row := q.db.QueryRow(ctx, createSubmission,
		arg.ID,
		arg.CampaignID,
		arg.ClipperID,
		arg.PostUrl,
		arg.Platform,
		arg.PlatformPostID,
	)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.ClipperID,
		&i.PostUrl,
		&i.Platform,
		&i.PlatformPostID,
		&i.Status,
		&i.RejectionReason,
		&i.ApprovedAt,
		&i.AutoApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, email, display_name, role)
VALUES ($1, $2, $3, $4)
RETURNING id, email, display_name, role, created_at, updated_at, upi_id, avatar_url, bio
`

type CreateUserParams struct {
	ID          string      `json:"id"`
	Email       string      `json:"email"`
	DisplayName pgtype.Text `json:"display_name"`
	Role        string      `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.DisplayName,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpiID,
		&i.AvatarUrl,
		&i.Bio,
	)
	return i, err
}

const deductCampaignBudget = `-- name: DeductCampaignBudget :one
UPDATE campaigns
SET remaining_budget = remaining_budget - $2, updated_at = NOW()
WHERE id = $1 AND remaining_budget >= $2
RETURNING id, owner_id, title, description, brief_url, platform, status, cpm_rate, total_budget, remaining_budget, platform_fee, escrow_id, max_clips_per_campaign, max_clips_per_clipper, min_views_per_clip, auto_approve_hours, starts_at, ends_at, created_at, updated_at
`

type DeductCampaignBudgetParams struct {
	ID              pgtype.UUID `json:"id"`
	RemainingBudget int32       `json:"remaining_budget"`
}

func (q *Queries) DeductCampaignBudget(ctx context.Context, arg DeductCampaignBudgetParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, deductCampaignBudget, arg.ID, arg.RemainingBudget)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Description,
		&i.BriefUrl,
		&i.Platform,
		&i.Status,
		&i.CpmRate,
		&i.TotalBudget,
		&i.RemainingBudget,
		&i.PlatformFee,
		&i.EscrowID,
		&i.MaxClipsPerCampaign,
		&i.MaxClipsPerClipper,
		&i.MinViewsPerClip,
		&i.AutoApproveHours,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteNotification = `-- name: DeleteNotification :exec
DELETE FROM notifications WHERE id = $1 AND user_id = $2
`

type DeleteNotificationParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID string      `json:"user_id"`
}

func (q *Queries) DeleteNotification(ctx context.Context, arg DeleteNotificationParams) error {
	_, err := q.db.Exec(ctx, deleteNotification, arg.ID, arg.UserID)
	return err
}

const deleteSocialAccount = `-- name: DeleteSocialAccount :exec
DELETE FROM social_accounts WHERE id = $1 AND user_id = $2
`

type DeleteSocialAccountParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID string      `json:"user_id"`
}

func (q *Queries) DeleteSocialAccount(ctx context.Context, arg DeleteSocialAccountParams) error {
	_, err := q.db.Exec(ctx, deleteSocialAccount, arg.ID, arg.UserID)
	return err
}

const getCampaignByID = `-- name: GetCampaignByID :one
SELECT id, owner_id, title, description, brief_url, platform, status, cpm_rate, total_budget, remaining_budget, platform_fee, escrow_id, max_clips_per_campaign, max_clips_per_clipper, min_views_per_clip, auto_approve_hours, starts_at, ends_at, created_at, updated_at FROM campaigns WHERE id = $1
`

func (q *Queries) GetCampaignByID(ctx context.Context, id pgtype.UUID) (Campaign, error) {
	row := q.db.QueryRow(ctx, getCampaignByID, id)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Description,
		&i.BriefUrl,
		&i.Platform,
		&i.Status,
		&i.CpmRate,
		&i.TotalBudget,
		&i.RemainingBudget,
		&i.PlatformFee,
		&i.EscrowID,
		&i.MaxClipsPerCampaign,
		&i.MaxClipsPerClipper,
		&i.MinViewsPerClip,
		&i.AutoApproveHours,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCampaignFinancialSummary = `-- name: GetCampaignFinancialSummary :one
SELECT
    COALESCE(SUM(CASE WHEN entry_type = 'earning' THEN amount ELSE 0 END), 0)::int as total_earnings,
    COALESCE(SUM(CASE WHEN entry_type = 'platform_fee' THEN amount ELSE 0 END), 0)::int as total_fees,
    COALESCE(SUM(CASE WHEN entry_type = 'refund' THEN ABS(amount) ELSE 0 END), 0)::int as total_refunds
FROM ledger_entries
WHERE campaign_id = $1
`

type GetCampaignFinancialSummaryRow struct {
	TotalEarnings int32 `json:"total_earnings"`
	TotalFees     int32 `json:"total_fees"`
	TotalRefunds  int32 `json:"total_refunds"`
}

func (q *Queries) GetCampaignFinancialSummary(ctx context.Context, campaignID pgtype.UUID) (GetCampaignFinancialSummaryRow, error) {
	row := q.db.QueryRow(ctx, getCampaignFinancialSummary, campaignID)
	var i GetCampaignFinancialSummaryRow
	err := row.Scan(&i.TotalEarnings, &i.TotalFees, &i.TotalRefunds)
	return i, err
}

const getCampaignSubmissionStats = `-- name: GetCampaignSubmissionStats :one

SELECT
    COUNT(*)::int as total_submissions,
    COUNT(*) FILTER (WHERE status = 'pending')::int as pending,
    COUNT(*) FILTER (WHERE status IN ('approved', 'auto_approved'))::int as approved,
    COUNT(*) FILTER (WHERE status = 'rejected')::int as rejected,
    COUNT(DISTINCT clipper_id)::int as unique_clippers
FROM submissions
WHERE campaign_id = $1
`

type GetCampaignSubmissionStatsRow struct {
	TotalSubmissions int32 `json:"total_submissions"`
	Pending          int32 `json:"pending"`
	Approved         int32 `json:"approved"`
	Rejected         int32 `json:"rejected"`
	UniqueClippers   int32 `json:"unique_clippers"`
}

// Campaign analytics queries
func (q *Queries) GetCampaignSubmissionStats(ctx context.Context, campaignID pgtype.UUID) (GetCampaignSubmissionStatsRow, error) {
	row := q.db.QueryRow(ctx, getCampaignSubmissionStats, campaignID)
	var i GetCampaignSubmissionStatsRow
	err := row.Scan(
		&i.TotalSubmissions,
		&i.Pending,
		&i.Approved,
		&i.Rejected,
		&i.UniqueClippers,
	)
	return i, err
}

const getCampaignTemplateByID = `-- name: GetCampaignTemplateByID :one
SELECT id, name, platform, cpm_rate, total_budget, max_clips_per_clipper, min_views_per_clip, auto_approve_hours, description_template, created_at FROM campaign_templates WHERE id = $1
`

func (q *Queries) GetCampaignTemplateByID(ctx context.Context, id pgtype.UUID) (CampaignTemplate, error) {
	row := q.db.QueryRow(ctx, getCampaignTemplateByID, id)
	var i CampaignTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Platform,
		&i.CpmRate,
		&i.TotalBudget,
		&i.MaxClipsPerClipper,
		&i.MinViewsPerClip,
		&i.AutoApproveHours,
		&i.DescriptionTemplate,
		&i.CreatedAt,
	)
	return i, err
}

const getCampaignViewStats = `-- name: GetCampaignViewStats :one
SELECT
    COALESCE(SUM(ms.views), 0)::bigint as total_views,
    COALESCE(SUM(ms.likes), 0)::bigint as total_likes,
    COALESCE(SUM(ms.comments), 0)::bigint as total_comments,
    COALESCE(SUM(ms.shares), 0)::bigint as total_shares
FROM metric_snapshots ms
JOIN submissions s ON ms.submission_id = s.id
WHERE s.campaign_id = $1
`

type GetCampaignViewStatsRow struct {
	TotalViews    int64 `json:"total_views"`
	TotalLikes    int64 `json:"total_likes"`
	TotalComments int64 `json:"total_comments"`
	TotalShares   int64 `json:"total_shares"`
}

func (q *Queries) GetCampaignViewStats(ctx context.Context, campaignID pgtype.UUID) (GetCampaignViewStatsRow, error) {
	row := q.db.QueryRow(ctx, getCampaignViewStats, campaignID)
	var i GetCampaignViewStatsRow
	err := row.Scan(
		&i.TotalViews,
		&i.TotalLikes,
		&i.TotalComments,
		&i.TotalShares,
	)
	return i, err
}

const getClipperCampaignCount = `-- name: GetClipperCampaignCount :one
SELECT COUNT(DISTINCT campaign_id)::int as campaigns_participated
FROM submissions
WHERE clipper_id = $1
`

func (q *Queries) GetClipperCampaignCount(ctx context.Context, clipperID string) (int32, error) {
	row := q.db.QueryRow(ctx, getClipperCampaignCount, clipperID)
	var campaigns_participated int32
	err := row.Scan(&campaigns_participated)
	return campaigns_participated, err
}

const getClipperSubmissionStats = `-- name: GetClipperSubmissionStats :one
SELECT
    COUNT(*)::int as total_submissions,
    COUNT(*) FILTER (WHERE status IN ('approved', 'auto_approved'))::int as approved_submissions,
    COUNT(*) FILTER (WHERE status = 'pending')::int as pending_submissions,
    COUNT(*) FILTER (WHERE status = 'rejected')::int as rejected_submissions
FROM submissions
WHERE clipper_id = $1
`

type GetClipperSubmissionStatsRow struct {
	TotalSubmissions    int32 `json:"total_submissions"`
	ApprovedSubmissions int32 `json:"approved_submissions"`
	PendingSubmissions  int32 `json:"pending_submissions"`
	RejectedSubmissions int32 `json:"rejected_submissions"`
}

func (q *Queries) GetClipperSubmissionStats(ctx context.Context, clipperID string) (GetClipperSubmissionStatsRow, error) {
	row := q.db.QueryRow(ctx, getClipperSubmissionStats, clipperID)
	var i GetClipperSubmissionStatsRow
	err := row.Scan(
		&i.TotalSubmissions,
		&i.ApprovedSubmissions,
		&i.PendingSubmissions,
		&i.RejectedSubmissions,
	)
	return i, err
}

const getClipperTotalEarnings = `-- name: GetClipperTotalEarnings :one
SELECT COALESCE(SUM(amount), 0)::int as total_earnings
FROM ledger_entries
WHERE clipper_id = $1 AND entry_type = 'earning'
`

func (q *Queries) GetClipperTotalEarnings(ctx context.Context, clipperID pgtype.Text) (int32, error) {
	row := q.db.QueryRow(ctx, getClipperTotalEarnings, clipperID)
	var total_earnings int32
	err := row.Scan(&total_earnings)
	return total_earnings, err
}

const getClipperTotalViews = `-- name: GetClipperTotalViews :one
SELECT COALESCE(SUM(ms.views), 0)::bigint as total_views
FROM metric_snapshots ms
JOIN submissions s ON ms.submission_id = s.id
WHERE s.clipper_id = $1
AND ms.id = (
    SELECT id FROM metric_snapshots
    WHERE submission_id = s.id
    ORDER BY captured_at DESC
    LIMIT 1
)
`

func (q *Queries) GetClipperTotalViews(ctx context.Context, clipperID string) (int64, error) {
	row := q.db.QueryRow(ctx, getClipperTotalViews, clipperID)
	var total_views int64
	err := row.Scan(&total_views)
	return total_views, err
}

const getFraudFlagByID = `-- name: GetFraudFlagByID :one
SELECT id, submission_id, user_id, flag_type, severity, description, status, resolved_by, resolution, created_at, resolved_at, updated_at FROM fraud_flags WHERE id = $1
`

func (q *Queries) GetFraudFlagByID(ctx context.Context, id pgtype.UUID) (FraudFlag, error) {
	row := q.db.QueryRow(ctx, getFraudFlagByID, id)
	var i FraudFlag
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.UserID,
		&i.FlagType,
		&i.Severity,
		&i.Description,
		&i.Status,
		&i.ResolvedBy,
		&i.Resolution,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInitialSnapshotForSubmission = `-- name: GetInitialSnapshotForSubmission :one
SELECT id, submission_id, platform, views, likes, comments, shares, captured_at, created_at FROM metric_snapshots
WHERE submission_id = $1
ORDER BY captured_at ASC
LIMIT 1
`

func (q *Queries) GetInitialSnapshotForSubmission(ctx context.Context, submissionID pgtype.UUID) (MetricSnapshot, error) {
	row := q.db.QueryRow(ctx, getInitialSnapshotForSubmission, submissionID)
	var i MetricSnapshot
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.Platform,
		&i.Views,
		&i.Likes,
		&i.Comments,
		&i.Shares,
		&i.CapturedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestSnapshotForSubmission = `-- name: GetLatestSnapshotForSubmission :one
SELECT id, submission_id, platform, views, likes, comments, shares, captured_at, created_at FROM metric_snapshots
WHERE submission_id = $1
ORDER BY captured_at DESC
LIMIT 1
`

func (q *Queries) GetLatestSnapshotForSubmission(ctx context.Context, submissionID pgtype.UUID) (MetricSnapshot, error) {
	row := q.db.QueryRow(ctx, getLatestSnapshotForSubmission, submissionID)
	var i MetricSnapshot
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.Platform,
		&i.Views,
		&i.Likes,
		&i.Comments,
		&i.Shares,
		&i.CapturedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getLeaderboardByEarnings = `-- name: GetLeaderboardByEarnings :many

SELECT
    u.id,
    u.display_name,
    u.avatar_url,
    COALESCE(SUM(le.amount), 0)::int as total_earnings,
    COUNT(DISTINCT s.id)::int as total_submissions,
    COUNT(DISTINCT s.campaign_id)::int as campaigns_participated
FROM users u
JOIN ledger_entries le ON le.clipper_id = u.id AND le.entry_type = 'earning'
JOIN submissions s ON s.clipper_id = u.id AND s.status IN ('approved', 'auto_approved')
WHERE u.role IN ('clipper', 'owner')
GROUP BY u.id, u.display_name, u.avatar_url
ORDER BY total_earnings DESC
LIMIT $1 OFFSET $2
`

type GetLeaderboardByEarningsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetLeaderboardByEarningsRow struct {
	ID                    string      `json:"id"`
	DisplayName           pgtype.Text `json:"display_name"`
	AvatarUrl             pgtype.Text `json:"avatar_url"`
	TotalEarnings         int32       `json:"total_earnings"`
	TotalSubmissions      int32       `json:"total_submissions"`
	CampaignsParticipated int32       `json:"campaigns_participated"`
}

// Leaderboard queries
func (q *Queries) GetLeaderboardByEarnings(ctx context.Context, arg GetLeaderboardByEarningsParams) ([]GetLeaderboardByEarningsRow, error) {
	rows, err := q.db.Query(ctx, getLeaderboardByEarnings, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLeaderboardByEarningsRow
	for rows.Next() {
		var i GetLeaderboardByEarningsRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.TotalEarnings,
			&i.TotalSubmissions,
			&i.CampaignsParticipated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLeaderboardBySubmissions = `-- name: GetLeaderboardBySubmissions :many
SELECT
    u.id,
    u.display_name,
    u.avatar_url,
    COUNT(s.id)::int as total_submissions,
    COUNT(*) FILTER (WHERE s.status IN ('approved', 'auto_approved'))::int as approved_submissions,
    COALESCE(SUM(le.amount), 0)::int as total_earnings
FROM users u
JOIN submissions s ON s.clipper_id = u.id
LEFT JOIN ledger_entries le ON le.clipper_id = u.id AND le.entry_type = 'earning'
WHERE u.role IN ('clipper', 'owner')
GROUP BY u.id, u.display_name, u.avatar_url
ORDER BY total_submissions DESC
LIMIT $1 OFFSET $2
`

type GetLeaderboardBySubmissionsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetLeaderboardBySubmissionsRow struct {
	ID                  string      `json:"id"`
	DisplayName         pgtype.Text `json:"display_name"`
	AvatarUrl           pgtype.Text `json:"avatar_url"`
	TotalSubmissions    int32       `json:"total_submissions"`
	ApprovedSubmissions int32       `json:"approved_submissions"`
	TotalEarnings       int32       `json:"total_earnings"`
}

func (q *Queries) GetLeaderboardBySubmissions(ctx context.Context, arg GetLeaderboardBySubmissionsParams) ([]GetLeaderboardBySubmissionsRow, error) {
	rows, err := q.db.Query(ctx, getLeaderboardBySubmissions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLeaderboardBySubmissionsRow
	for rows.Next() {
		var i GetLeaderboardBySubmissionsRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.TotalSubmissions,
			&i.ApprovedSubmissions,
			&i.TotalEarnings,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLedgerEntryByIdempotencyKey = `-- name: GetLedgerEntryByIdempotencyKey :one
SELECT id, idempotency_key, entry_type, campaign_id, submission_id, clipper_id, amount, description, metadata, created_at FROM ledger_entries WHERE idempotency_key = $1
`

func (q *Queries) GetLedgerEntryByIdempotencyKey(ctx context.Context, idempotencyKey string) (LedgerEntry, error) {
	row := q.db.QueryRow(ctx, getLedgerEntryByIdempotencyKey, idempotencyKey)
	var i LedgerEntry
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.EntryType,
		&i.CampaignID,
		&i.SubmissionID,
		&i.ClipperID,
		&i.Amount,
		&i.Description,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getPayoutRequestByID = `-- name: GetPayoutRequestByID :one
SELECT id, clipper_id, amount, upi_id, status, provider_ref, failure_reason, idempotency_key, created_at, processed_at, updated_at FROM payout_requests WHERE id = $1
`

func (q *Queries) GetPayoutRequestByID(ctx context.Context, id pgtype.UUID) (PayoutRequest, error) {
	row := q.db.QueryRow(ctx, getPayoutRequestByID, id)
	var i PayoutRequest
	err := row.Scan(
		&i.ID,
		&i.ClipperID,
		&i.Amount,
		&i.UpiID,
		&i.Status,
		&i.ProviderRef,
		&i.FailureReason,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.ProcessedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSocialAccountByPlatformAndUser = `-- name: GetSocialAccountByPlatformAndUser :one

SELECT id, user_id, platform, platform_user_id, platform_username, access_token, refresh_token, token_expires_at, created_at, updated_at FROM social_accounts WHERE user_id = $1 AND platform = $2
`

type GetSocialAccountByPlatformAndUserParams struct {
	UserID   string `json:"user_id"`
	Platform string `json:"platform"`
}

// Social account queries
func (q *Queries) GetSocialAccountByPlatformAndUser(ctx context.Context, arg GetSocialAccountByPlatformAndUserParams) (SocialAccount, error) {
	row := q.db.QueryRow(ctx, getSocialAccountByPlatformAndUser, arg.UserID, arg.Platform)
	var i SocialAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Platform,
		&i.PlatformUserID,
		&i.PlatformUsername,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubmissionByID = `-- name: GetSubmissionByID :one
SELECT id, campaign_id, clipper_id, post_url, platform, platform_post_id, status, rejection_reason, approved_at, auto_approved_at, created_at, updated_at FROM submissions WHERE id = $1
`

func (q *Queries) GetSubmissionByID(ctx context.Context, id pgtype.UUID) (Submission, error) {
	row := q.db.QueryRow(ctx, getSubmissionByID, id)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.ClipperID,
		&i.PostUrl,
		&i.Platform,
		&i.PlatformPostID,
		&i.Status,
		&i.RejectionReason,
		&i.ApprovedAt,
		&i.AutoApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubmissionWithCampaign = `-- name: GetSubmissionWithCampaign :one
SELECT s.id, s.campaign_id, s.clipper_id, s.post_url, s.platform, s.platform_post_id, s.status, s.rejection_reason, s.approved_at, s.auto_approved_at, s.created_at, s.updated_at, c.min_views_per_clip, c.cpm_rate, c.owner_id
FROM submissions s
JOIN campaigns c ON s.campaign_id = c.id
WHERE s.id = $1
`

type GetSubmissionWithCampaignRow struct {
	ID              pgtype.UUID        `json:"id"`
	CampaignID      pgtype.UUID        `json:"campaign_id"`
	ClipperID       string             `json:"clipper_id"`
	PostUrl         string             `json:"post_url"`
	Platform        string             `json:"platform"`
	PlatformPostID  pgtype.Text        `json:"platform_post_id"`
	Status          string             `json:"status"`
	RejectionReason pgtype.Text        `json:"rejection_reason"`
	ApprovedAt      pgtype.Timestamptz `json:"approved_at"`
	AutoApprovedAt  pgtype.Timestamptz `json:"auto_approved_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	MinViewsPerClip pgtype.Int4        `json:"min_views_per_clip"`
	CpmRate         int32              `json:"cpm_rate"`
	OwnerID         string             `json:"owner_id"`
}

func (q *Queries) GetSubmissionWithCampaign(ctx context.Context, id pgtype.UUID) (GetSubmissionWithCampaignRow, error) {
	row := q.db.QueryRow(ctx, getSubmissionWithCampaign, id)
	var i GetSubmissionWithCampaignRow
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.ClipperID,
		&i.PostUrl,
		&i.Platform,
		&i.PlatformPostID,
		&i.Status,
		&i.RejectionReason,
		&i.ApprovedAt,
		&i.AutoApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MinViewsPerClip,
		&i.CpmRate,
		&i.OwnerID,
	)
	return i, err
}

const getSubmissionsNeedingVerification = `-- name: GetSubmissionsNeedingVerification :many
SELECT s.id, s.campaign_id, s.clipper_id, s.post_url, s.platform, s.platform_post_id, s.status, s.rejection_reason, s.approved_at, s.auto_approved_at, s.created_at, s.updated_at, c.min_views_per_clip, c.cpm_rate, c.owner_id
FROM submissions s
JOIN campaigns c ON s.campaign_id = c.id
WHERE s.status IN ('approved', 'auto_approved')
  AND s.id NOT IN (
    SELECT submission_id FROM metric_snapshots
    WHERE captured_at > NOW() - INTERVAL '1 hour'
  )
LIMIT $1
`

type GetSubmissionsNeedingVerificationRow struct {
	ID              pgtype.UUID        `json:"id"`
	CampaignID      pgtype.UUID        `json:"campaign_id"`
	ClipperID       string             `json:"clipper_id"`
	PostUrl         string             `json:"post_url"`
	Platform        string             `json:"platform"`
	PlatformPostID  pgtype.Text        `json:"platform_post_id"`
	Status          string             `json:"status"`
	RejectionReason pgtype.Text        `json:"rejection_reason"`
	ApprovedAt      pgtype.Timestamptz `json:"approved_at"`
	AutoApprovedAt  pgtype.Timestamptz `json:"auto_approved_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	MinViewsPerClip pgtype.Int4        `json:"min_views_per_clip"`
	CpmRate         int32              `json:"cpm_rate"`
	OwnerID         string             `json:"owner_id"`
}

func (q *Queries) GetSubmissionsNeedingVerification(ctx context.Context, limit int32) ([]GetSubmissionsNeedingVerificationRow, error) {
	rows, err := q.db.Query(ctx, getSubmissionsNeedingVerification, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSubmissionsNeedingVerificationRow
	for rows.Next() {
		var i GetSubmissionsNeedingVerificationRow
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.ClipperID,
			&i.PostUrl,
			&i.Platform,
			&i.PlatformPostID,
			&i.Status,
			&i.RejectionReason,
			&i.ApprovedAt,
			&i.AutoApprovedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MinViewsPerClip,
			&i.CpmRate,
			&i.OwnerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, display_name, role, created_at, updated_at, upi_id, avatar_url, bio FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpiID,
		&i.AvatarUrl,
		&i.Bio,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, display_name, role, created_at, updated_at, upi_id, avatar_url, bio FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpiID,
		&i.AvatarUrl,
		&i.Bio,
	)
	return i, err
}

const getUserPublicProfile = `-- name: GetUserPublicProfile :one


SELECT id, display_name, avatar_url, bio, created_at FROM users WHERE id = $1
`

type GetUserPublicProfileRow struct {
	ID          string             `json:"id"`
	DisplayName pgtype.Text        `json:"display_name"`
	AvatarUrl   pgtype.Text        `json:"avatar_url"`
	Bio         pgtype.Text        `json:"bio"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

// Admin user queries
// Clipper public profile queries
func (q *Queries) GetUserPublicProfile(ctx context.Context, id string) (GetUserPublicProfileRow, error) {
	row := q.db.QueryRow(ctx, getUserPublicProfile, id)
	var i GetUserPublicProfileRow
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Bio,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveCampaigns = `-- name: ListActiveCampaigns :many
SELECT id, owner_id, title, description, brief_url, platform, status, cpm_rate, total_budget, remaining_budget, platform_fee, escrow_id, max_clips_per_campaign, max_clips_per_clipper, min_views_per_clip, auto_approve_hours, starts_at, ends_at, created_at, updated_at FROM campaigns
WHERE status IN ('active', 'funded')
  AND (ends_at IS NULL OR ends_at > NOW())
ORDER BY created_at DESC
`

func (q *Queries) ListActiveCampaigns(ctx context.Context) ([]Campaign, error) {
	rows, err := q.db.Query(ctx, listActiveCampaigns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Campaign
	for rows.Next() {
		var i Campaign
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Title,
			&i.Description,
			&i.BriefUrl,
			&i.Platform,
			&i.Status,
			&i.CpmRate,
			&i.TotalBudget,
			&i.RemainingBudget,
			&i.PlatformFee,
			&i.EscrowID,
			&i.MaxClipsPerCampaign,
			&i.MaxClipsPerClipper,
			&i.MinViewsPerClip,
			&i.AutoApproveHours,
			&i.StartsAt,
			&i.EndsAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, actor_id, action, resource_type, resource_id, details, ip_address, created_at FROM audit_logs
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAuditLogsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.Details,
			&i.IpAddress,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsByActor = `-- name: ListAuditLogsByActor :many
SELECT id, actor_id, action, resource_type, resource_id, details, ip_address, created_at FROM audit_logs
WHERE actor_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListAuditLogsByActorParams struct {
	ActorID string `json:"actor_id"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) ListAuditLogsByActor(ctx context.Context, arg ListAuditLogsByActorParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogsByActor, arg.ActorID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.Details,
			&i.IpAddress,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsByResource = `-- name: ListAuditLogsByResource :many
SELECT id, actor_id, action, resource_type, resource_id, details, ip_address, created_at FROM audit_logs
WHERE resource_type = $1 AND resource_id = $2
ORDER BY created_at DESC
`

type ListAuditLogsByResourceParams struct {
	ResourceType string `json:"resource_type"`
	ResourceID   string `json:"resource_id"`
}

func (q *Queries) ListAuditLogsByResource(ctx context.Context, arg ListAuditLogsByResourceParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogsByResource, arg.ResourceType, arg.ResourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.Details,
			&i.IpAddress,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCampaignTemplates = `-- name: ListCampaignTemplates :many

SELECT id, name, platform, cpm_rate, total_budget, max_clips_per_clipper, min_views_per_clip, auto_approve_hours, description_template, created_at FROM campaign_templates ORDER BY created_at DESC
`

// Campaign template queries
func (q *Queries) ListCampaignTemplates(ctx context.Context) ([]CampaignTemplate, error) {
	rows, err := q.db.Query(ctx, listCampaignTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CampaignTemplate
	for rows.Next() {
		var i CampaignTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Platform,
			&i.CpmRate,
			&i.TotalBudget,
			&i.MaxClipsPerClipper,
			&i.MinViewsPerClip,
			&i.AutoApproveHours,
			&i.DescriptionTemplate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCampaignsByOwner = `-- name: ListCampaignsByOwner :many
SELECT id, owner_id, title, description, brief_url, platform, status, cpm_rate, total_budget, remaining_budget, platform_fee, escrow_id, max_clips_per_campaign, max_clips_per_clipper, min_views_per_clip, auto_approve_hours, starts_at, ends_at, created_at, updated_at FROM campaigns
WHERE owner_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListCampaignsByOwner(ctx context.Context, ownerID string) ([]Campaign, error) {
	rows, err := q.db.Query(ctx, listCampaignsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Campaign
	for rows.Next() {
		var i Campaign
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Title,
			&i.Description,
			&i.BriefUrl,
			&i.Platform,
			&i.Status,
			&i.CpmRate,
			&i.TotalBudget,
			&i.RemainingBudget,
			&i.PlatformFee,
			&i.EscrowID,
			&i.MaxClipsPerCampaign,
			&i.MaxClipsPerClipper,
			&i.MinViewsPerClip,
			&i.AutoApproveHours,
			&i.StartsAt,
			&i.EndsAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCampaignsFiltered = `-- name: ListCampaignsFiltered :many
SELECT id, owner_id, title, description, brief_url, platform, status, cpm_rate, total_budget, remaining_budget, platform_fee, escrow_id, max_clips_per_campaign, max_clips_per_clipper, min_views_per_clip, auto_approve_hours, starts_at, ends_at, created_at, updated_at FROM campaigns
WHERE status IN ('active', 'funded')
  AND (ends_at IS NULL OR ends_at > NOW())
  AND ($1::text = '' OR platform = $1)
  AND ($2::int = 0 OR cpm_rate <= $2)
  AND ($3::int = 0 OR remaining_budget >= $3)
  AND ($4::text = '' OR title ILIKE '%' || $4 || '%' OR description ILIKE '%' || $4 || '%')
ORDER BY created_at DESC
LIMIT $5 OFFSET $6
`

type ListCampaignsFilteredParams struct {
	Column1 string `json:"column_1"`
	Column2 int32  `json:"column_2"`
	Column3 int32  `json:"column_3"`
	Column4 string `json:"column_4"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) ListCampaignsFiltered(ctx context.Context, arg ListCampaignsFilteredParams) ([]Campaign, error) {
	rows, err := q.db.Query(ctx, listCampaignsFiltered,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Campaign
	for rows.Next() {
		var i Campaign
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Title,
			&i.Description,
			&i.BriefUrl,
			&i.Platform,
			&i.Status,
			&i.CpmRate,
			&i.TotalBudget,
			&i.RemainingBudget,
			&i.PlatformFee,
			&i.EscrowID,
			&i.MaxClipsPerCampaign,
			&i.MaxClipsPerClipper,
			&i.MinViewsPerClip,
			&i.AutoApproveHours,
			&i.StartsAt,
			&i.EndsAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFraudFlagsByUser = `-- name: ListFraudFlagsByUser :many
SELECT id, submission_id, user_id, flag_type, severity, description, status, resolved_by, resolution, created_at, resolved_at, updated_at FROM fraud_flags
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListFraudFlagsByUser(ctx context.Context, userID pgtype.Text) ([]FraudFlag, error) {
	rows, err := q.db.Query(ctx, listFraudFlagsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FraudFlag
	for rows.Next() {
		var i FraudFlag
		if err := rows.Scan(
			&i.ID,
			&i.SubmissionID,
			&i.UserID,
			&i.FlagType,
			&i.Severity,
			&i.Description,
			&i.Status,
			&i.ResolvedBy,
			&i.Resolution,
			&i.CreatedAt,
			&i.ResolvedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLedgerEntriesByCampaign = `-- name: ListLedgerEntriesByCampaign :many
SELECT id, idempotency_key, entry_type, campaign_id, submission_id, clipper_id, amount, description, metadata, created_at FROM ledger_entries WHERE campaign_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListLedgerEntriesByCampaign(ctx context.Context, campaignID pgtype.UUID) ([]LedgerEntry, error) {
	rows, err := q.db.Query(ctx, listLedgerEntriesByCampaign, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LedgerEntry
	for rows.Next() {
		var i LedgerEntry
		if err := rows.Scan(
			&i.ID,
			&i.IdempotencyKey,
			&i.EntryType,
			&i.CampaignID,
			&i.SubmissionID,
			&i.ClipperID,
			&i.Amount,
			&i.Description,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLedgerEntriesByClipper = `-- name: ListLedgerEntriesByClipper :many
SELECT id, idempotency_key, entry_type, campaign_id, submission_id, clipper_id, amount, description, metadata, created_at FROM ledger_entries WHERE clipper_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListLedgerEntriesByClipper(ctx context.Context, clipperID pgtype.Text) ([]LedgerEntry, error) {
	rows, err := q.db.Query(ctx, listLedgerEntriesByClipper, clipperID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LedgerEntry
	for rows.Next() {
		var i LedgerEntry
		if err := rows.Scan(
			&i.ID,
			&i.IdempotencyKey,
			&i.EntryType,
			&i.CampaignID,
			&i.SubmissionID,
			&i.ClipperID,
			&i.Amount,
			&i.Description,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationsByUser = `-- name: ListNotificationsByUser :many
SELECT id, user_id, type, title, body, link, is_read, created_at FROM notifications WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListNotificationsByUserParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListNotificationsByUser(ctx context.Context, arg ListNotificationsByUserParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotificationsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.Link,
			&i.IsRead,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenFraudFlags = `-- name: ListOpenFraudFlags :many
SELECT id, submission_id, user_id, flag_type, severity, description, status, resolved_by, resolution, created_at, resolved_at, updated_at FROM fraud_flags
WHERE status = 'open'
ORDER BY
  CASE severity WHEN 'critical' THEN 0 WHEN 'high' THEN 1 WHEN 'medium' THEN 2 ELSE 3 END,
  created_at ASC
`

func (q *Queries) ListOpenFraudFlags(ctx context.Context) ([]FraudFlag, error) {
	rows, err := q.db.Query(ctx, listOpenFraudFlags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FraudFlag
	for rows.Next() {
		var i FraudFlag
		if err := rows.Scan(
			&i.ID,
			&i.SubmissionID,
			&i.UserID,
			&i.FlagType,
			&i.Severity,
			&i.Description,
			&i.Status,
			&i.ResolvedBy,
			&i.Resolution,
			&i.CreatedAt,
			&i.ResolvedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPayoutRequestsByClipper = `-- name: ListPayoutRequestsByClipper :many
SELECT id, clipper_id, amount, upi_id, status, provider_ref, failure_reason, idempotency_key, created_at, processed_at, updated_at FROM payout_requests WHERE clipper_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListPayoutRequestsByClipper(ctx context.Context, clipperID string) ([]PayoutRequest, error) {
	rows, err := q.db.Query(ctx, listPayoutRequestsByClipper, clipperID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PayoutRequest
	for rows.Next() {
		var i PayoutRequest
		if err := rows.Scan(
			&i.ID,
			&i.ClipperID,
			&i.Amount,
			&i.UpiID,
			&i.Status,
			&i.ProviderRef,
			&i.FailureReason,
			&i.IdempotencyKey,
			&i.CreatedAt,
			&i.ProcessedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPayoutsByUser = `-- name: ListPayoutsByUser :many
SELECT id, clipper_id, amount, upi_id, status, provider_ref, failure_reason, idempotency_key, created_at, processed_at, updated_at FROM payout_requests
WHERE clipper_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListPayoutsByUser(ctx context.Context, clipperID string) ([]PayoutRequest, error) {
	rows, err := q.db.Query(ctx, listPayoutsByUser, clipperID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PayoutRequest
	for rows.Next() {
		var i PayoutRequest
		if err := rows.Scan(
			&i.ID,
			&i.ClipperID,
			&i.Amount,
			&i.UpiID,
			&i.Status,
			&i.ProviderRef,
			&i.FailureReason,
			&i.IdempotencyKey,
			&i.CreatedAt,
			&i.ProcessedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingPayoutRequests = `-- name: ListPendingPayoutRequests :many
SELECT id, clipper_id, amount, upi_id, status, provider_ref, failure_reason, idempotency_key, created_at, processed_at, updated_at FROM payout_requests WHERE status = 'pending' ORDER BY created_at ASC
`

func (q *Queries) ListPendingPayoutRequests(ctx context.Context) ([]PayoutRequest, error) {
	rows, err := q.db.Query(ctx, listPendingPayoutRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PayoutRequest
	for rows.Next() {
		var i PayoutRequest
		if err := rows.Scan(
			&i.ID,
			&i.ClipperID,
			&i.Amount,
			&i.UpiID,
			&i.Status,
			&i.ProviderRef,
			&i.FailureReason,
			&i.IdempotencyKey,
			&i.CreatedAt,
			&i.ProcessedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingSubmissionsOlderThan = `-- name: ListPendingSubmissionsOlderThan :many
SELECT s.id, s.campaign_id, s.clipper_id, s.post_url, s.platform, s.platform_post_id, s.status, s.rejection_reason, s.approved_at, s.auto_approved_at, s.created_at, s.updated_at, c.auto_approve_hours, c.owner_id
FROM submissions s
JOIN campaigns c ON c.id = s.campaign_id
WHERE s.status = 'pending'
  AND s.created_at < $1
ORDER BY s.created_at ASC
`

type ListPendingSubmissionsOlderThanRow struct {
	ID               pgtype.UUID        `json:"id"`
	CampaignID       pgtype.UUID        `json:"campaign_id"`
	ClipperID        string             `json:"clipper_id"`
	PostUrl          string             `json:"post_url"`
	Platform         string             `json:"platform"`
	PlatformPostID   pgtype.Text        `json:"platform_post_id"`
	Status           string             `json:"status"`
	RejectionReason  pgtype.Text        `json:"rejection_reason"`
	ApprovedAt       pgtype.Timestamptz `json:"approved_at"`
	AutoApprovedAt   pgtype.Timestamptz `json:"auto_approved_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	AutoApproveHours pgtype.Int4        `json:"auto_approve_hours"`
	OwnerID          string             `json:"owner_id"`
}

func (q *Queries) ListPendingSubmissionsOlderThan(ctx context.Context, createdAt pgtype.Timestamptz) ([]ListPendingSubmissionsOlderThanRow, error) {
	rows, err := q.db.Query(ctx, listPendingSubmissionsOlderThan, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingSubmissionsOlderThanRow
	for rows.Next() {
		var i ListPendingSubmissionsOlderThanRow
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.ClipperID,
			&i.PostUrl,
			&i.Platform,
			&i.PlatformPostID,
			&i.Status,
			&i.RejectionReason,
			&i.ApprovedAt,
			&i.AutoApprovedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AutoApproveHours,
			&i.OwnerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSnapshotsBySubmission = `-- name: ListSnapshotsBySubmission :many
SELECT id, submission_id, platform, views, likes, comments, shares, captured_at, created_at FROM metric_snapshots
WHERE submission_id = $1
ORDER BY captured_at ASC
`

func (q *Queries) ListSnapshotsBySubmission(ctx context.Context, submissionID pgtype.UUID) ([]MetricSnapshot, error) {
	rows, err := q.db.Query(ctx, listSnapshotsBySubmission, submissionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MetricSnapshot
	for rows.Next() {
		var i MetricSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.SubmissionID,
			&i.Platform,
			&i.Views,
			&i.Likes,
			&i.Comments,
			&i.Shares,
			&i.CapturedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSocialAccountsByUserID = `-- name: ListSocialAccountsByUserID :many
SELECT id, user_id, platform, platform_user_id, platform_username, access_token, refresh_token, token_expires_at, created_at, updated_at FROM social_accounts
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListSocialAccountsByUserID(ctx context.Context, userID string) ([]SocialAccount, error) {
	rows, err := q.db.Query(ctx, listSocialAccountsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SocialAccount
	for rows.Next() {
		var i SocialAccount
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Platform,
			&i.PlatformUserID,
			&i.PlatformUsername,
			&i.AccessToken,
			&i.RefreshToken,
			&i.TokenExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSocialAccountsByUserIDPublic = `-- name: ListSocialAccountsByUserIDPublic :many
SELECT platform, platform_username FROM social_accounts WHERE user_id = $1
`

type ListSocialAccountsByUserIDPublicRow struct {
	Platform         string      `json:"platform"`
	PlatformUsername pgtype.Text `json:"platform_username"`
}

func (q *Queries) ListSocialAccountsByUserIDPublic(ctx context.Context, userID string) ([]ListSocialAccountsByUserIDPublicRow, error) {
	rows, err := q.db.Query(ctx, listSocialAccountsByUserIDPublic, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSocialAccountsByUserIDPublicRow
	for rows.Next() {
		var i ListSocialAccountsByUserIDPublicRow
		if err := rows.Scan(&i.Platform, &i.PlatformUsername); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubmissionsByCampaign = `-- name: ListSubmissionsByCampaign :many
SELECT id, campaign_id, clipper_id, post_url, platform, platform_post_id, status, rejection_reason, approved_at, auto_approved_at, created_at, updated_at FROM submissions
WHERE campaign_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListSubmissionsByCampaign(ctx context.Context, campaignID pgtype.UUID) ([]Submission, error) {
	rows, err := q.db.Query(ctx, listSubmissionsByCampaign, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Submission
	for rows.Next() {
		var i Submission
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.ClipperID,
			&i.PostUrl,
			&i.Platform,
			&i.PlatformPostID,
			&i.Status,
			&i.RejectionReason,
			&i.ApprovedAt,
			&i.AutoApprovedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubmissionsByClipper = `-- name: ListSubmissionsByClipper :many
SELECT id, campaign_id, clipper_id, post_url, platform, platform_post_id, status, rejection_reason, approved_at, auto_approved_at, created_at, updated_at FROM submissions
WHERE clipper_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListSubmissionsByClipper(ctx context.Context, clipperID string) ([]Submission, error) {
	rows, err := q.db.Query(ctx, listSubmissionsByClipper, clipperID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Submission
	for rows.Next() {
		var i Submission
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.ClipperID,
			&i.PostUrl,
			&i.Platform,
			&i.PlatformPostID,
			&i.Status,
			&i.RejectionReason,
			&i.ApprovedAt,
			&i.AutoApprovedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubmissionsByUser = `-- name: ListSubmissionsByUser :many
SELECT id, campaign_id, clipper_id, post_url, platform, platform_post_id, status, rejection_reason, approved_at, auto_approved_at, created_at, updated_at FROM submissions
WHERE clipper_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListSubmissionsByUser(ctx context.Context, clipperID string) ([]Submission, error) {
	rows, err := q.db.Query(ctx, listSubmissionsByUser, clipperID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Submission
	for rows.Next() {
		var i Submission
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.ClipperID,
			&i.PostUrl,
			&i.Platform,
			&i.PlatformPostID,
			&i.Status,
			&i.RejectionReason,
			&i.ApprovedAt,
			&i.AutoApprovedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many

SELECT id, email, display_name, role, created_at, updated_at, upi_id, avatar_url, bio FROM users
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// Admin user queries
func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.DisplayName,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UpiID,
			&i.AvatarUrl,
			&i.Bio,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersWithManyFlags = `-- name: ListUsersWithManyFlags :many
SELECT u.id, u.email, u.display_name, u.role, u.created_at, u.updated_at, u.upi_id, COUNT(f.id)::int as flag_count
FROM users u
JOIN fraud_flags f ON f.user_id = u.id
WHERE f.status = 'open'
GROUP BY u.id
HAVING COUNT(f.id) >= $1::int
ORDER BY COUNT(f.id) DESC
`

type ListUsersWithManyFlagsRow struct {
	ID          string             `json:"id"`
	Email       string             `json:"email"`
	DisplayName pgtype.Text        `json:"display_name"`
	Role        string             `json:"role"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	UpiID       pgtype.Text        `json:"upi_id"`
	FlagCount   int32              `json:"flag_count"`
}

func (q *Queries) ListUsersWithManyFlags(ctx context.Context, dollar_1 int32) ([]ListUsersWithManyFlagsRow, error) {
	rows, err := q.db.Query(ctx, listUsersWithManyFlags, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersWithManyFlagsRow
	for rows.Next() {
		var i ListUsersWithManyFlagsRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.DisplayName,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UpiID,
			&i.FlagCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
UPDATE notifications SET is_read = true WHERE user_id = $1 AND is_read = false
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, markAllNotificationsRead, userID)
	return err
}

const markNotificationRead = `-- name: MarkNotificationRead :exec
UPDATE notifications SET is_read = true WHERE id = $1 AND user_id = $2
`

type MarkNotificationReadParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID string      `json:"user_id"`
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) error {
	_, err := q.db.Exec(ctx, markNotificationRead, arg.ID, arg.UserID)
	return err
}

const sumEarningsByClipper = `-- name: SumEarningsByClipper :one
SELECT COALESCE(SUM(amount), 0)::bigint as total FROM ledger_entries
WHERE clipper_id = $1 AND entry_type = 'earning'
`

func (q *Queries) SumEarningsByClipper(ctx context.Context, clipperID pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, sumEarningsByClipper, clipperID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const sumEarningsByClipperForCampaign = `-- name: SumEarningsByClipperForCampaign :one
SELECT COALESCE(SUM(amount), 0)::bigint as total FROM ledger_entries
WHERE clipper_id = $1 AND campaign_id = $2 AND entry_type = 'earning'
`

type SumEarningsByClipperForCampaignParams struct {
	ClipperID  pgtype.Text `json:"clipper_id"`
	CampaignID pgtype.UUID `json:"campaign_id"`
}

func (q *Queries) SumEarningsByClipperForCampaign(ctx context.Context, arg SumEarningsByClipperForCampaignParams) (int64, error) {
	row := q.db.QueryRow(ctx, sumEarningsByClipperForCampaign, arg.ClipperID, arg.CampaignID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const sumFeesByCampaign = `-- name: SumFeesByCampaign :one
SELECT COALESCE(SUM(amount), 0)::bigint as total FROM ledger_entries
WHERE campaign_id = $1 AND entry_type = 'platform_fee'
`

func (q *Queries) SumFeesByCampaign(ctx context.Context, campaignID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, sumFeesByCampaign, campaignID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const sumPendingPayoutsByClipper = `-- name: SumPendingPayoutsByClipper :one
SELECT COALESCE(SUM(amount), 0)::bigint as total FROM payout_requests
WHERE clipper_id = $1 AND status IN ('pending', 'processing')
`

func (q *Queries) SumPendingPayoutsByClipper(ctx context.Context, clipperID string) (int64, error) {
	row := q.db.QueryRow(ctx, sumPendingPayoutsByClipper, clipperID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const sumSpendByCampaign = `-- name: SumSpendByCampaign :one
SELECT COALESCE(SUM(amount), 0)::bigint as total FROM ledger_entries
WHERE campaign_id = $1 AND entry_type = 'earning'
`

func (q *Queries) SumSpendByCampaign(ctx context.Context, campaignID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, sumSpendByCampaign, campaignID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const updateCampaign = `-- name: UpdateCampaign :one
UPDATE campaigns
SET title = $2, description = $3, brief_url = $4, max_clips_per_campaign = $5,
    max_clips_per_clipper = $6, min_views_per_clip = $7, auto_approve_hours = $8,
    ends_at = $9, updated_at = NOW()
WHERE id = $1
RETURNING id, owner_id, title, description, brief_url, platform, status, cpm_rate, total_budget, remaining_budget, platform_fee, escrow_id, max_clips_per_campaign, max_clips_per_clipper, min_views_per_clip, auto_approve_hours, starts_at, ends_at, created_at, updated_at
`

type UpdateCampaignParams struct {
	ID                  pgtype.UUID        `json:"id"`
	Title               string             `json:"title"`
	Description         pgtype.Text        `json:"description"`
	BriefUrl            pgtype.Text        `json:"brief_url"`
	MaxClipsPerCampaign pgtype.Int4        `json:"max_clips_per_campaign"`
	MaxClipsPerClipper  pgtype.Int4        `json:"max_clips_per_clipper"`
	MinViewsPerClip     pgtype.Int4        `json:"min_views_per_clip"`
	AutoApproveHours    pgtype.Int4        `json:"auto_approve_hours"`
	EndsAt              pgtype.Timestamptz `json:"ends_at"`
}

func (q *Queries) UpdateCampaign(ctx context.Context, arg UpdateCampaignParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, updateCampaign,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.BriefUrl,
		arg.MaxClipsPerCampaign,
		arg.MaxClipsPerClipper,
		arg.MinViewsPerClip,
		arg.AutoApproveHours,
		arg.EndsAt,
	)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Description,
		&i.BriefUrl,
		&i.Platform,
		&i.Status,
		&i.CpmRate,
		&i.TotalBudget,
		&i.RemainingBudget,
		&i.PlatformFee,
		&i.EscrowID,
		&i.MaxClipsPerCampaign,
		&i.MaxClipsPerClipper,
		&i.MinViewsPerClip,
		&i.AutoApproveHours,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCampaignBudget = `-- name: UpdateCampaignBudget :one
UPDATE campaigns
SET remaining_budget = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, owner_id, title, description, brief_url, platform, status, cpm_rate, total_budget, remaining_budget, platform_fee, escrow_id, max_clips_per_campaign, max_clips_per_clipper, min_views_per_clip, auto_approve_hours, starts_at, ends_at, created_at, updated_at
`

type UpdateCampaignBudgetParams struct {
	ID              pgtype.UUID `json:"id"`
	RemainingBudget int32       `json:"remaining_budget"`
}

func (q *Queries) UpdateCampaignBudget(ctx context.Context, arg UpdateCampaignBudgetParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, updateCampaignBudget, arg.ID, arg.RemainingBudget)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Description,
		&i.BriefUrl,
		&i.Platform,
		&i.Status,
		&i.CpmRate,
		&i.TotalBudget,
		&i.RemainingBudget,
		&i.PlatformFee,
		&i.EscrowID,
		&i.MaxClipsPerCampaign,
		&i.MaxClipsPerClipper,
		&i.MinViewsPerClip,
		&i.AutoApproveHours,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCampaignStatus = `-- name: UpdateCampaignStatus :one
UPDATE campaigns
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, owner_id, title, description, brief_url, platform, status, cpm_rate, total_budget, remaining_budget, platform_fee, escrow_id, max_clips_per_campaign, max_clips_per_clipper, min_views_per_clip, auto_approve_hours, starts_at, ends_at, created_at, updated_at
`

type UpdateCampaignStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateCampaignStatus(ctx context.Context, arg UpdateCampaignStatusParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, updateCampaignStatus, arg.ID, arg.Status)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Description,
		&i.BriefUrl,
		&i.Platform,
		&i.Status,
		&i.CpmRate,
		&i.TotalBudget,
		&i.RemainingBudget,
		&i.PlatformFee,
		&i.EscrowID,
		&i.MaxClipsPerCampaign,
		&i.MaxClipsPerClipper,
		&i.MinViewsPerClip,
		&i.AutoApproveHours,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateFraudFlagStatus = `-- name: UpdateFraudFlagStatus :one
UPDATE fraud_flags
SET status = $2, resolved_by = $3, resolution = $4,
    resolved_at = CASE WHEN $2 IN ('resolved', 'dismissed') THEN NOW() ELSE resolved_at END,
    updated_at = NOW()
WHERE id = $1
RETURNING id, submission_id, user_id, flag_type, severity, description, status, resolved_by, resolution, created_at, resolved_at, updated_at
`

type UpdateFraudFlagStatusParams struct {
	ID         pgtype.UUID `json:"id"`
	Status     string      `json:"status"`
	ResolvedBy pgtype.Text `json:"resolved_by"`
	Resolution pgtype.Text `json:"resolution"`
}

func (q *Queries) UpdateFraudFlagStatus(ctx context.Context, arg UpdateFraudFlagStatusParams) (FraudFlag, error) {
	row := q.db.QueryRow(ctx, updateFraudFlagStatus,
		arg.ID,
		arg.Status,
		arg.ResolvedBy,
		arg.Resolution,
	)
	var i FraudFlag
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.UserID,
		&i.FlagType,
		&i.Severity,
		&i.Description,
		&i.Status,
		&i.ResolvedBy,
		&i.Resolution,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePayoutRequestStatus = `-- name: UpdatePayoutRequestStatus :one
UPDATE payout_requests
SET status = $2, provider_ref = $3, failure_reason = $4,
    processed_at = CASE WHEN $2 IN ('completed', 'failed') THEN NOW() ELSE processed_at END,
    updated_at = NOW()
WHERE id = $1
RETURNING id, clipper_id, amount, upi_id, status, provider_ref, failure_reason, idempotency_key, created_at, processed_at, updated_at
`

type UpdatePayoutRequestStatusParams struct {
	ID            pgtype.UUID `json:"id"`
	Status        string      `json:"status"`
	ProviderRef   pgtype.Text `json:"provider_ref"`
	FailureReason pgtype.Text `json:"failure_reason"`
}

func (q *Queries) UpdatePayoutRequestStatus(ctx context.Context, arg UpdatePayoutRequestStatusParams) (PayoutRequest, error) {
	row := q.db.QueryRow(ctx, updatePayoutRequestStatus,
		arg.ID,
		arg.Status,
		arg.ProviderRef,
		arg.FailureReason,
	)
	var i PayoutRequest
	err := row.Scan(
		&i.ID,
		&i.ClipperID,
		&i.Amount,
		&i.UpiID,
		&i.Status,
		&i.ProviderRef,
		&i.FailureReason,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.ProcessedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSubmissionStatus = `-- name: UpdateSubmissionStatus :one
UPDATE submissions
SET status = $2,
    rejection_reason = $3,
    approved_at = CASE WHEN $2 = 'approved' THEN NOW() ELSE approved_at END,
    auto_approved_at = CASE WHEN $2 = 'auto_approved' THEN NOW() ELSE auto_approved_at END,
    updated_at = NOW()
WHERE id = $1
RETURNING id, campaign_id, clipper_id, post_url, platform, platform_post_id, status, rejection_reason, approved_at, auto_approved_at, created_at, updated_at
`

type UpdateSubmissionStatusParams struct {
	ID              pgtype.UUID `json:"id"`
	Status          string      `json:"status"`
	RejectionReason pgtype.Text `json:"rejection_reason"`
}

func (q *Queries) UpdateSubmissionStatus(ctx context.Context, arg UpdateSubmissionStatusParams) (Submission, error) {
	row := q.db.QueryRow(ctx, updateSubmissionStatus, arg.ID, arg.Status, arg.RejectionReason)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.ClipperID,
		&i.PostUrl,
		&i.Platform,
		&i.PlatformPostID,
		&i.Status,
		&i.RejectionReason,
		&i.ApprovedAt,
		&i.AutoApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET display_name = COALESCE($2, display_name),
    email = COALESCE($3, email),
    updated_at = NOW()
WHERE id = $1
RETURNING id, email, display_name, role, created_at, updated_at, upi_id, avatar_url, bio
`

type UpdateUserParams struct {
	ID          string      `json:"id"`
	DisplayName pgtype.Text `json:"display_name"`
	Email       string      `json:"email"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.ID, arg.DisplayName, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpiID,
		&i.AvatarUrl,
		&i.Bio,
	)
	return i, err
}

const updateUserRole = `-- name: UpdateUserRole :one
UPDATE users
SET role = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, email, display_name, role, created_at, updated_at, upi_id, avatar_url, bio
`

type UpdateUserRoleParams struct {
	ID   string `json:"id"`
	Role string `json:"role"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserRole, arg.ID, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpiID,
		&i.AvatarUrl,
		&i.Bio,
	)
	return i, err
}

const updateUserUPI = `-- name: UpdateUserUPI :one

UPDATE users SET upi_id = $2, updated_at = NOW() WHERE id = $1 RETURNING id, email, display_name, role, created_at, updated_at, upi_id, avatar_url, bio
`

type UpdateUserUPIParams struct {
	ID    string      `json:"id"`
	UpiID pgtype.Text `json:"upi_id"`
}

// Payout queries
func (q *Queries) UpdateUserUPI(ctx context.Context, arg UpdateUserUPIParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserUPI, arg.ID, arg.UpiID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpiID,
		&i.AvatarUrl,
		&i.Bio,
	)
	return i, err
}

const upsertSocialAccount = `-- name: UpsertSocialAccount :one
INSERT INTO social_accounts (user_id, platform, platform_user_id, platform_username, access_token, refresh_token, token_expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (platform, platform_user_id) DO UPDATE SET
    platform_username = EXCLUDED.platform_username,
    access_token = EXCLUDED.access_token,
    refresh_token = EXCLUDED.refresh_token,
    token_expires_at = EXCLUDED.token_expires_at,
    updated_at = NOW()
RETURNING id, user_id, platform, platform_user_id, platform_username, access_token, refresh_token, token_expires_at, created_at, updated_at
`

type UpsertSocialAccountParams struct {
	UserID           string             `json:"user_id"`
	Platform         string             `json:"platform"`
	PlatformUserID   string             `json:"platform_user_id"`
	PlatformUsername pgtype.Text        `json:"platform_username"`
	AccessToken      pgtype.Text        `json:"access_token"`
	RefreshToken     pgtype.Text        `json:"refresh_token"`
	TokenExpiresAt   pgtype.Timestamptz `json:"token_expires_at"`
}

func (q *Queries) UpsertSocialAccount(ctx context.Context, arg UpsertSocialAccountParams) (SocialAccount, error) {
	row := q.db.QueryRow(ctx, upsertSocialAccount,
		arg.UserID,
		arg.Platform,
		arg.PlatformUserID,
		arg.PlatformUsername,
		arg.AccessToken,
		arg.RefreshToken,
		arg.TokenExpiresAt,
	)
	var i SocialAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Platform,
		&i.PlatformUserID,
		&i.PlatformUsername,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
