// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountCampaignsFiltered(ctx context.Context, arg CountCampaignsFilteredParams) (int64, error)
	CountSnapshotsBySubmission(ctx context.Context, submissionID pgtype.UUID) (int64, error)
	CountSubmissionsByCampaign(ctx context.Context, campaignID pgtype.UUID) (int64, error)
	CountSubmissionsByClipperForCampaign(ctx context.Context, arg CountSubmissionsByClipperForCampaignParams) (int64, error)
	CreateCampaign(ctx context.Context, arg CreateCampaignParams) (Campaign, error)
	CreateLedgerEntry(ctx context.Context, arg CreateLedgerEntryParams) (LedgerEntry, error)
	CreateMetricSnapshot(ctx context.Context, arg CreateMetricSnapshotParams) (MetricSnapshot, error)
	CreateSocialAccount(ctx context.Context, arg CreateSocialAccountParams) (SocialAccount, error)
	CreateSubmission(ctx context.Context, arg CreateSubmissionParams) (Submission, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteSocialAccount(ctx context.Context, arg DeleteSocialAccountParams) error
	GetCampaignByID(ctx context.Context, id pgtype.UUID) (Campaign, error)
	GetInitialSnapshotForSubmission(ctx context.Context, submissionID pgtype.UUID) (MetricSnapshot, error)
	GetLatestSnapshotForSubmission(ctx context.Context, submissionID pgtype.UUID) (MetricSnapshot, error)
	GetLedgerEntryByIdempotencyKey(ctx context.Context, idempotencyKey string) (LedgerEntry, error)
	GetSubmissionByID(ctx context.Context, id pgtype.UUID) (Submission, error)
	GetSubmissionWithCampaign(ctx context.Context, id pgtype.UUID) (GetSubmissionWithCampaignRow, error)
	GetSubmissionsNeedingVerification(ctx context.Context, limit int32) ([]GetSubmissionsNeedingVerificationRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	ListActiveCampaigns(ctx context.Context) ([]Campaign, error)
	ListCampaignsByOwner(ctx context.Context, ownerID string) ([]Campaign, error)
	ListCampaignsFiltered(ctx context.Context, arg ListCampaignsFilteredParams) ([]Campaign, error)
	ListLedgerEntriesByCampaign(ctx context.Context, campaignID pgtype.UUID) ([]LedgerEntry, error)
	ListLedgerEntriesByClipper(ctx context.Context, clipperID pgtype.Text) ([]LedgerEntry, error)
	ListPendingSubmissionsOlderThan(ctx context.Context, createdAt pgtype.Timestamptz) ([]ListPendingSubmissionsOlderThanRow, error)
	ListSnapshotsBySubmission(ctx context.Context, submissionID pgtype.UUID) ([]MetricSnapshot, error)
	ListSocialAccountsByUserID(ctx context.Context, userID string) ([]SocialAccount, error)
	ListSubmissionsByCampaign(ctx context.Context, campaignID pgtype.UUID) ([]Submission, error)
	ListSubmissionsByClipper(ctx context.Context, clipperID string) ([]Submission, error)
	SumEarningsByClipper(ctx context.Context, clipperID pgtype.Text) (int64, error)
	SumEarningsByClipperForCampaign(ctx context.Context, arg SumEarningsByClipperForCampaignParams) (int64, error)
	SumFeesByCampaign(ctx context.Context, campaignID pgtype.UUID) (int64, error)
	SumSpendByCampaign(ctx context.Context, campaignID pgtype.UUID) (int64, error)
	UpdateCampaignBudget(ctx context.Context, arg UpdateCampaignBudgetParams) (Campaign, error)
	UpdateCampaignStatus(ctx context.Context, arg UpdateCampaignStatusParams) (Campaign, error)
	UpdateSubmissionStatus(ctx context.Context, arg UpdateSubmissionStatusParams) (Submission, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error)
}

var _ Querier = (*Queries)(nil)
