// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCampaignsFiltered = `-- name: CountCampaignsFiltered :one
SELECT COUNT(*) FROM campaigns
WHERE status IN ('active', 'funded')
  AND (ends_at IS NULL OR ends_at > NOW())
  AND ($1::text = '' OR platform = $1)
  AND ($2::int = 0 OR cpm_rate <= $2)
  AND ($3::int = 0 OR remaining_budget >= $3)
`

type CountCampaignsFilteredParams struct {
	Column1 string `json:"column_1"`
	Column2 int32  `json:"column_2"`
	Column3 int32  `json:"column_3"`
}

func (q *Queries) CountCampaignsFiltered(ctx context.Context, arg CountCampaignsFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCampaignsFiltered, arg.Column1, arg.Column2, arg.Column3)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSnapshotsBySubmission = `-- name: CountSnapshotsBySubmission :one
SELECT COUNT(*) FROM metric_snapshots
WHERE submission_id = $1
`

func (q *Queries) CountSnapshotsBySubmission(ctx context.Context, submissionID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countSnapshotsBySubmission, submissionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSubmissionsByCampaign = `-- name: CountSubmissionsByCampaign :one
SELECT COUNT(*) FROM submissions WHERE campaign_id = $1
`

func (q *Queries) CountSubmissionsByCampaign(ctx context.Context, campaignID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countSubmissionsByCampaign, campaignID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSubmissionsByClipperForCampaign = `-- name: CountSubmissionsByClipperForCampaign :one
SELECT COUNT(*) FROM submissions WHERE campaign_id = $1 AND clipper_id = $2
`

type CountSubmissionsByClipperForCampaignParams struct {
	CampaignID pgtype.UUID `json:"campaign_id"`
	ClipperID  string      `json:"clipper_id"`
}

func (q *Queries) CountSubmissionsByClipperForCampaign(ctx context.Context, arg CountSubmissionsByClipperForCampaignParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSubmissionsByClipperForCampaign, arg.CampaignID, arg.ClipperID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCampaign = `-- name: CreateCampaign :one
INSERT INTO campaigns (
    id, owner_id, title, description, brief_url, platform, status,
    cpm_rate, total_budget, remaining_budget, platform_fee, escrow_id,
    max_clips_per_campaign, max_clips_per_clipper, min_views_per_clip,
    auto_approve_hours, starts_at, ends_at
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11, $12,
    $13, $14, $15, $16, $17, $18
)
RETURNING id, owner_id, title, description, brief_url, platform, status, cpm_rate, total_budget, remaining_budget, platform_fee, escrow_id, max_clips_per_campaign, max_clips_per_clipper, min_views_per_clip, auto_approve_hours, starts_at, ends_at, created_at, updated_at
`

type CreateCampaignParams struct {
	ID                  pgtype.UUID        `json:"id"`
	OwnerID             string             `json:"owner_id"`
	Title               string             `json:"title"`
	Description         pgtype.Text        `json:"description"`
	BriefUrl            pgtype.Text        `json:"brief_url"`
	Platform            string             `json:"platform"`
	Status              string             `json:"status"`
	CpmRate             int32              `json:"cpm_rate"`
	TotalBudget         int32              `json:"total_budget"`
	RemainingBudget     int32              `json:"remaining_budget"`
	PlatformFee         int32              `json:"platform_fee"`
	EscrowID            pgtype.Text        `json:"escrow_id"`
	MaxClipsPerCampaign pgtype.Int4        `json:"max_clips_per_campaign"`
	MaxClipsPerClipper  pgtype.Int4        `json:"max_clips_per_clipper"`
	MinViewsPerClip     pgtype.Int4        `json:"min_views_per_clip"`
	AutoApproveHours    pgtype.Int4        `json:"auto_approve_hours"`
	StartsAt            pgtype.Timestamptz `json:"starts_at"`
	EndsAt              pgtype.Timestamptz `json:"ends_at"`
}

func (q *Queries) CreateCampaign(ctx context.Context, arg CreateCampaignParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, createCampaign,
		arg.ID,
		arg.OwnerID,
		arg.Title,
		arg.Description,
		arg.BriefUrl,
		arg.Platform,
		arg.Status,
		arg.CpmRate,
		arg.TotalBudget,
		arg.RemainingBudget,
		arg.PlatformFee,
		arg.EscrowID,
		arg.MaxClipsPerCampaign,
		arg.MaxClipsPerClipper,
		arg.MinViewsPerClip,
		arg.AutoApproveHours,
		arg.StartsAt,
		arg.EndsAt,
	)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Description,
		&i.BriefUrl,
		&i.Platform,
		&i.Status,
		&i.CpmRate,
		&i.TotalBudget,
		&i.RemainingBudget,
		&i.PlatformFee,
		&i.EscrowID,
		&i.MaxClipsPerCampaign,
		&i.MaxClipsPerClipper,
		&i.MinViewsPerClip,
		&i.AutoApproveHours,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMetricSnapshot = `-- name: CreateMetricSnapshot :one
INSERT INTO metric_snapshots (submission_id, platform, views, likes, comments, shares, captured_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, submission_id, platform, views, likes, comments, shares, captured_at, created_at
`

type CreateMetricSnapshotParams struct {
	SubmissionID pgtype.UUID        `json:"submission_id"`
	Platform     string             `json:"platform"`
	Views        int64              `json:"views"`
	Likes        int64              `json:"likes"`
	Comments     int64              `json:"comments"`
	Shares       int64              `json:"shares"`
	CapturedAt   pgtype.Timestamptz `json:"captured_at"`
}

func (q *Queries) CreateMetricSnapshot(ctx context.Context, arg CreateMetricSnapshotParams) (MetricSnapshot, error) {
	row := q.db.QueryRow(ctx, createMetricSnapshot,
		arg.SubmissionID,
		arg.Platform,
		arg.Views,
		arg.Likes,
		arg.Comments,
		arg.Shares,
		arg.CapturedAt,
	)
	var i MetricSnapshot
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.Platform,
		&i.Views,
		&i.Likes,
		&i.Comments,
		&i.Shares,
		&i.CapturedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createSocialAccount = `-- name: CreateSocialAccount :one
INSERT INTO social_accounts (user_id, platform, platform_user_id, platform_username, access_token, refresh_token, token_expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, platform, platform_user_id, platform_username, access_token, refresh_token, token_expires_at, created_at, updated_at
`

type CreateSocialAccountParams struct {
	UserID           string             `json:"user_id"`
	Platform         string             `json:"platform"`
	PlatformUserID   string             `json:"platform_user_id"`
	PlatformUsername pgtype.Text        `json:"platform_username"`
	AccessToken      pgtype.Text        `json:"access_token"`
	RefreshToken     pgtype.Text        `json:"refresh_token"`
	TokenExpiresAt   pgtype.Timestamptz `json:"token_expires_at"`
}

func (q *Queries) CreateSocialAccount(ctx context.Context, arg CreateSocialAccountParams) (SocialAccount, error) {
	row := q.db.QueryRow(ctx, createSocialAccount,
		arg.UserID,
		arg.Platform,
		arg.PlatformUserID,
		arg.PlatformUsername,
		arg.AccessToken,
		arg.RefreshToken,
		arg.TokenExpiresAt,
	)
	var i SocialAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Platform,
		&i.PlatformUserID,
		&i.PlatformUsername,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSubmission = `-- name: CreateSubmission :one
INSERT INTO submissions (id, campaign_id, clipper_id, post_url, platform, platform_post_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, campaign_id, clipper_id, post_url, platform, platform_post_id, status, rejection_reason, approved_at, auto_approved_at, created_at, updated_at
`

type CreateSubmissionParams struct {
	ID             pgtype.UUID `json:"id"`
	CampaignID     pgtype.UUID `json:"campaign_id"`
	ClipperID      string      `json:"clipper_id"`
	PostUrl        string      `json:"post_url"`
	Platform       string      `json:"platform"`
	PlatformPostID pgtype.Text `json:"platform_post_id"`
}

func (q *Queries) CreateSubmission(ctx context.Context, arg CreateSubmissionParams) (Submission, error) {
	row := q.db.QueryRow(ctx, createSubmission,
		arg.ID,
		arg.CampaignID,
		arg.ClipperID,
		arg.PostUrl,
		arg.Platform,
		arg.PlatformPostID,
	)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.ClipperID,
		&i.PostUrl,
		&i.Platform,
		&i.PlatformPostID,
		&i.Status,
		&i.RejectionReason,
		&i.ApprovedAt,
		&i.AutoApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, email, display_name, role)
VALUES ($1, $2, $3, $4)
RETURNING id, email, display_name, role, created_at, updated_at
`

type CreateUserParams struct {
	ID          string      `json:"id"`
	Email       string      `json:"email"`
	DisplayName pgtype.Text `json:"display_name"`
	Role        string      `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.DisplayName,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSocialAccount = `-- name: DeleteSocialAccount :exec
DELETE FROM social_accounts WHERE id = $1 AND user_id = $2
`

type DeleteSocialAccountParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID string      `json:"user_id"`
}

func (q *Queries) DeleteSocialAccount(ctx context.Context, arg DeleteSocialAccountParams) error {
	_, err := q.db.Exec(ctx, deleteSocialAccount, arg.ID, arg.UserID)
	return err
}

const getCampaignByID = `-- name: GetCampaignByID :one
SELECT id, owner_id, title, description, brief_url, platform, status, cpm_rate, total_budget, remaining_budget, platform_fee, escrow_id, max_clips_per_campaign, max_clips_per_clipper, min_views_per_clip, auto_approve_hours, starts_at, ends_at, created_at, updated_at FROM campaigns WHERE id = $1
`

func (q *Queries) GetCampaignByID(ctx context.Context, id pgtype.UUID) (Campaign, error) {
	row := q.db.QueryRow(ctx, getCampaignByID, id)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Description,
		&i.BriefUrl,
		&i.Platform,
		&i.Status,
		&i.CpmRate,
		&i.TotalBudget,
		&i.RemainingBudget,
		&i.PlatformFee,
		&i.EscrowID,
		&i.MaxClipsPerCampaign,
		&i.MaxClipsPerClipper,
		&i.MinViewsPerClip,
		&i.AutoApproveHours,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInitialSnapshotForSubmission = `-- name: GetInitialSnapshotForSubmission :one
SELECT id, submission_id, platform, views, likes, comments, shares, captured_at, created_at FROM metric_snapshots
WHERE submission_id = $1
ORDER BY captured_at ASC
LIMIT 1
`

func (q *Queries) GetInitialSnapshotForSubmission(ctx context.Context, submissionID pgtype.UUID) (MetricSnapshot, error) {
	row := q.db.QueryRow(ctx, getInitialSnapshotForSubmission, submissionID)
	var i MetricSnapshot
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.Platform,
		&i.Views,
		&i.Likes,
		&i.Comments,
		&i.Shares,
		&i.CapturedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestSnapshotForSubmission = `-- name: GetLatestSnapshotForSubmission :one
SELECT id, submission_id, platform, views, likes, comments, shares, captured_at, created_at FROM metric_snapshots
WHERE submission_id = $1
ORDER BY captured_at DESC
LIMIT 1
`

func (q *Queries) GetLatestSnapshotForSubmission(ctx context.Context, submissionID pgtype.UUID) (MetricSnapshot, error) {
	row := q.db.QueryRow(ctx, getLatestSnapshotForSubmission, submissionID)
	var i MetricSnapshot
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.Platform,
		&i.Views,
		&i.Likes,
		&i.Comments,
		&i.Shares,
		&i.CapturedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSubmissionByID = `-- name: GetSubmissionByID :one
SELECT id, campaign_id, clipper_id, post_url, platform, platform_post_id, status, rejection_reason, approved_at, auto_approved_at, created_at, updated_at FROM submissions WHERE id = $1
`

func (q *Queries) GetSubmissionByID(ctx context.Context, id pgtype.UUID) (Submission, error) {
	row := q.db.QueryRow(ctx, getSubmissionByID, id)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.ClipperID,
		&i.PostUrl,
		&i.Platform,
		&i.PlatformPostID,
		&i.Status,
		&i.RejectionReason,
		&i.ApprovedAt,
		&i.AutoApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubmissionWithCampaign = `-- name: GetSubmissionWithCampaign :one
SELECT s.id, s.campaign_id, s.clipper_id, s.post_url, s.platform, s.platform_post_id, s.status, s.rejection_reason, s.approved_at, s.auto_approved_at, s.created_at, s.updated_at, c.min_views_per_clip, c.cpm_rate, c.owner_id
FROM submissions s
JOIN campaigns c ON s.campaign_id = c.id
WHERE s.id = $1
`

type GetSubmissionWithCampaignRow struct {
	ID              pgtype.UUID        `json:"id"`
	CampaignID      pgtype.UUID        `json:"campaign_id"`
	ClipperID       string             `json:"clipper_id"`
	PostUrl         string             `json:"post_url"`
	Platform        string             `json:"platform"`
	PlatformPostID  pgtype.Text        `json:"platform_post_id"`
	Status          string             `json:"status"`
	RejectionReason pgtype.Text        `json:"rejection_reason"`
	ApprovedAt      pgtype.Timestamptz `json:"approved_at"`
	AutoApprovedAt  pgtype.Timestamptz `json:"auto_approved_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	MinViewsPerClip pgtype.Int4        `json:"min_views_per_clip"`
	CpmRate         int32              `json:"cpm_rate"`
	OwnerID         string             `json:"owner_id"`
}

func (q *Queries) GetSubmissionWithCampaign(ctx context.Context, id pgtype.UUID) (GetSubmissionWithCampaignRow, error) {
	row := q.db.QueryRow(ctx, getSubmissionWithCampaign, id)
	var i GetSubmissionWithCampaignRow
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.ClipperID,
		&i.PostUrl,
		&i.Platform,
		&i.PlatformPostID,
		&i.Status,
		&i.RejectionReason,
		&i.ApprovedAt,
		&i.AutoApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MinViewsPerClip,
		&i.CpmRate,
		&i.OwnerID,
	)
	return i, err
}

const getSubmissionsNeedingVerification = `-- name: GetSubmissionsNeedingVerification :many
SELECT s.id, s.campaign_id, s.clipper_id, s.post_url, s.platform, s.platform_post_id, s.status, s.rejection_reason, s.approved_at, s.auto_approved_at, s.created_at, s.updated_at, c.min_views_per_clip, c.cpm_rate, c.owner_id
FROM submissions s
JOIN campaigns c ON s.campaign_id = c.id
WHERE s.status IN ('approved', 'auto_approved')
  AND s.id NOT IN (
    SELECT submission_id FROM metric_snapshots
    WHERE captured_at > NOW() - INTERVAL '1 hour'
  )
LIMIT $1
`

type GetSubmissionsNeedingVerificationRow struct {
	ID              pgtype.UUID        `json:"id"`
	CampaignID      pgtype.UUID        `json:"campaign_id"`
	ClipperID       string             `json:"clipper_id"`
	PostUrl         string             `json:"post_url"`
	Platform        string             `json:"platform"`
	PlatformPostID  pgtype.Text        `json:"platform_post_id"`
	Status          string             `json:"status"`
	RejectionReason pgtype.Text        `json:"rejection_reason"`
	ApprovedAt      pgtype.Timestamptz `json:"approved_at"`
	AutoApprovedAt  pgtype.Timestamptz `json:"auto_approved_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	MinViewsPerClip pgtype.Int4        `json:"min_views_per_clip"`
	CpmRate         int32              `json:"cpm_rate"`
	OwnerID         string             `json:"owner_id"`
}

func (q *Queries) GetSubmissionsNeedingVerification(ctx context.Context, limit int32) ([]GetSubmissionsNeedingVerificationRow, error) {
	rows, err := q.db.Query(ctx, getSubmissionsNeedingVerification, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSubmissionsNeedingVerificationRow
	for rows.Next() {
		var i GetSubmissionsNeedingVerificationRow
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.ClipperID,
			&i.PostUrl,
			&i.Platform,
			&i.PlatformPostID,
			&i.Status,
			&i.RejectionReason,
			&i.ApprovedAt,
			&i.AutoApprovedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MinViewsPerClip,
			&i.CpmRate,
			&i.OwnerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, display_name, role, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, display_name, role, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveCampaigns = `-- name: ListActiveCampaigns :many
SELECT id, owner_id, title, description, brief_url, platform, status, cpm_rate, total_budget, remaining_budget, platform_fee, escrow_id, max_clips_per_campaign, max_clips_per_clipper, min_views_per_clip, auto_approve_hours, starts_at, ends_at, created_at, updated_at FROM campaigns
WHERE status IN ('active', 'funded')
  AND (ends_at IS NULL OR ends_at > NOW())
ORDER BY created_at DESC
`

func (q *Queries) ListActiveCampaigns(ctx context.Context) ([]Campaign, error) {
	rows, err := q.db.Query(ctx, listActiveCampaigns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Campaign
	for rows.Next() {
		var i Campaign
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Title,
			&i.Description,
			&i.BriefUrl,
			&i.Platform,
			&i.Status,
			&i.CpmRate,
			&i.TotalBudget,
			&i.RemainingBudget,
			&i.PlatformFee,
			&i.EscrowID,
			&i.MaxClipsPerCampaign,
			&i.MaxClipsPerClipper,
			&i.MinViewsPerClip,
			&i.AutoApproveHours,
			&i.StartsAt,
			&i.EndsAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCampaignsByOwner = `-- name: ListCampaignsByOwner :many
SELECT id, owner_id, title, description, brief_url, platform, status, cpm_rate, total_budget, remaining_budget, platform_fee, escrow_id, max_clips_per_campaign, max_clips_per_clipper, min_views_per_clip, auto_approve_hours, starts_at, ends_at, created_at, updated_at FROM campaigns
WHERE owner_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListCampaignsByOwner(ctx context.Context, ownerID string) ([]Campaign, error) {
	rows, err := q.db.Query(ctx, listCampaignsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Campaign
	for rows.Next() {
		var i Campaign
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Title,
			&i.Description,
			&i.BriefUrl,
			&i.Platform,
			&i.Status,
			&i.CpmRate,
			&i.TotalBudget,
			&i.RemainingBudget,
			&i.PlatformFee,
			&i.EscrowID,
			&i.MaxClipsPerCampaign,
			&i.MaxClipsPerClipper,
			&i.MinViewsPerClip,
			&i.AutoApproveHours,
			&i.StartsAt,
			&i.EndsAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCampaignsFiltered = `-- name: ListCampaignsFiltered :many
SELECT id, owner_id, title, description, brief_url, platform, status, cpm_rate, total_budget, remaining_budget, platform_fee, escrow_id, max_clips_per_campaign, max_clips_per_clipper, min_views_per_clip, auto_approve_hours, starts_at, ends_at, created_at, updated_at FROM campaigns
WHERE status IN ('active', 'funded')
  AND (ends_at IS NULL OR ends_at > NOW())
  AND ($1::text = '' OR platform = $1)
  AND ($2::int = 0 OR cpm_rate <= $2)
  AND ($3::int = 0 OR remaining_budget >= $3)
ORDER BY created_at DESC
LIMIT $4 OFFSET $5
`

type ListCampaignsFilteredParams struct {
	Column1 string `json:"column_1"`
	Column2 int32  `json:"column_2"`
	Column3 int32  `json:"column_3"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) ListCampaignsFiltered(ctx context.Context, arg ListCampaignsFilteredParams) ([]Campaign, error) {
	rows, err := q.db.Query(ctx, listCampaignsFiltered,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Campaign
	for rows.Next() {
		var i Campaign
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Title,
			&i.Description,
			&i.BriefUrl,
			&i.Platform,
			&i.Status,
			&i.CpmRate,
			&i.TotalBudget,
			&i.RemainingBudget,
			&i.PlatformFee,
			&i.EscrowID,
			&i.MaxClipsPerCampaign,
			&i.MaxClipsPerClipper,
			&i.MinViewsPerClip,
			&i.AutoApproveHours,
			&i.StartsAt,
			&i.EndsAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingSubmissionsOlderThan = `-- name: ListPendingSubmissionsOlderThan :many
SELECT s.id, s.campaign_id, s.clipper_id, s.post_url, s.platform, s.platform_post_id, s.status, s.rejection_reason, s.approved_at, s.auto_approved_at, s.created_at, s.updated_at, c.auto_approve_hours, c.owner_id
FROM submissions s
JOIN campaigns c ON c.id = s.campaign_id
WHERE s.status = 'pending'
  AND s.created_at < $1
ORDER BY s.created_at ASC
`

type ListPendingSubmissionsOlderThanRow struct {
	ID               pgtype.UUID        `json:"id"`
	CampaignID       pgtype.UUID        `json:"campaign_id"`
	ClipperID        string             `json:"clipper_id"`
	PostUrl          string             `json:"post_url"`
	Platform         string             `json:"platform"`
	PlatformPostID   pgtype.Text        `json:"platform_post_id"`
	Status           string             `json:"status"`
	RejectionReason  pgtype.Text        `json:"rejection_reason"`
	ApprovedAt       pgtype.Timestamptz `json:"approved_at"`
	AutoApprovedAt   pgtype.Timestamptz `json:"auto_approved_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	AutoApproveHours pgtype.Int4        `json:"auto_approve_hours"`
	OwnerID          string             `json:"owner_id"`
}

func (q *Queries) ListPendingSubmissionsOlderThan(ctx context.Context, createdAt pgtype.Timestamptz) ([]ListPendingSubmissionsOlderThanRow, error) {
	rows, err := q.db.Query(ctx, listPendingSubmissionsOlderThan, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingSubmissionsOlderThanRow
	for rows.Next() {
		var i ListPendingSubmissionsOlderThanRow
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.ClipperID,
			&i.PostUrl,
			&i.Platform,
			&i.PlatformPostID,
			&i.Status,
			&i.RejectionReason,
			&i.ApprovedAt,
			&i.AutoApprovedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AutoApproveHours,
			&i.OwnerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSnapshotsBySubmission = `-- name: ListSnapshotsBySubmission :many
SELECT id, submission_id, platform, views, likes, comments, shares, captured_at, created_at FROM metric_snapshots
WHERE submission_id = $1
ORDER BY captured_at ASC
`

func (q *Queries) ListSnapshotsBySubmission(ctx context.Context, submissionID pgtype.UUID) ([]MetricSnapshot, error) {
	rows, err := q.db.Query(ctx, listSnapshotsBySubmission, submissionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MetricSnapshot
	for rows.Next() {
		var i MetricSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.SubmissionID,
			&i.Platform,
			&i.Views,
			&i.Likes,
			&i.Comments,
			&i.Shares,
			&i.CapturedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSocialAccountsByUserID = `-- name: ListSocialAccountsByUserID :many
SELECT id, user_id, platform, platform_user_id, platform_username, access_token, refresh_token, token_expires_at, created_at, updated_at FROM social_accounts
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListSocialAccountsByUserID(ctx context.Context, userID string) ([]SocialAccount, error) {
	rows, err := q.db.Query(ctx, listSocialAccountsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SocialAccount
	for rows.Next() {
		var i SocialAccount
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Platform,
			&i.PlatformUserID,
			&i.PlatformUsername,
			&i.AccessToken,
			&i.RefreshToken,
			&i.TokenExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubmissionsByCampaign = `-- name: ListSubmissionsByCampaign :many
SELECT id, campaign_id, clipper_id, post_url, platform, platform_post_id, status, rejection_reason, approved_at, auto_approved_at, created_at, updated_at FROM submissions
WHERE campaign_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListSubmissionsByCampaign(ctx context.Context, campaignID pgtype.UUID) ([]Submission, error) {
	rows, err := q.db.Query(ctx, listSubmissionsByCampaign, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Submission
	for rows.Next() {
		var i Submission
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.ClipperID,
			&i.PostUrl,
			&i.Platform,
			&i.PlatformPostID,
			&i.Status,
			&i.RejectionReason,
			&i.ApprovedAt,
			&i.AutoApprovedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubmissionsByClipper = `-- name: ListSubmissionsByClipper :many
SELECT id, campaign_id, clipper_id, post_url, platform, platform_post_id, status, rejection_reason, approved_at, auto_approved_at, created_at, updated_at FROM submissions
WHERE clipper_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListSubmissionsByClipper(ctx context.Context, clipperID string) ([]Submission, error) {
	rows, err := q.db.Query(ctx, listSubmissionsByClipper, clipperID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Submission
	for rows.Next() {
		var i Submission
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.ClipperID,
			&i.PostUrl,
			&i.Platform,
			&i.PlatformPostID,
			&i.Status,
			&i.RejectionReason,
			&i.ApprovedAt,
			&i.AutoApprovedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCampaignBudget = `-- name: UpdateCampaignBudget :one
UPDATE campaigns
SET remaining_budget = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, owner_id, title, description, brief_url, platform, status, cpm_rate, total_budget, remaining_budget, platform_fee, escrow_id, max_clips_per_campaign, max_clips_per_clipper, min_views_per_clip, auto_approve_hours, starts_at, ends_at, created_at, updated_at
`

type UpdateCampaignBudgetParams struct {
	ID              pgtype.UUID `json:"id"`
	RemainingBudget int32       `json:"remaining_budget"`
}

func (q *Queries) UpdateCampaignBudget(ctx context.Context, arg UpdateCampaignBudgetParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, updateCampaignBudget, arg.ID, arg.RemainingBudget)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Description,
		&i.BriefUrl,
		&i.Platform,
		&i.Status,
		&i.CpmRate,
		&i.TotalBudget,
		&i.RemainingBudget,
		&i.PlatformFee,
		&i.EscrowID,
		&i.MaxClipsPerCampaign,
		&i.MaxClipsPerClipper,
		&i.MinViewsPerClip,
		&i.AutoApproveHours,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCampaignStatus = `-- name: UpdateCampaignStatus :one
UPDATE campaigns
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, owner_id, title, description, brief_url, platform, status, cpm_rate, total_budget, remaining_budget, platform_fee, escrow_id, max_clips_per_campaign, max_clips_per_clipper, min_views_per_clip, auto_approve_hours, starts_at, ends_at, created_at, updated_at
`

type UpdateCampaignStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateCampaignStatus(ctx context.Context, arg UpdateCampaignStatusParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, updateCampaignStatus, arg.ID, arg.Status)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Description,
		&i.BriefUrl,
		&i.Platform,
		&i.Status,
		&i.CpmRate,
		&i.TotalBudget,
		&i.RemainingBudget,
		&i.PlatformFee,
		&i.EscrowID,
		&i.MaxClipsPerCampaign,
		&i.MaxClipsPerClipper,
		&i.MinViewsPerClip,
		&i.AutoApproveHours,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSubmissionStatus = `-- name: UpdateSubmissionStatus :one
UPDATE submissions
SET status = $2,
    rejection_reason = $3,
    approved_at = CASE WHEN $2 = 'approved' THEN NOW() ELSE approved_at END,
    auto_approved_at = CASE WHEN $2 = 'auto_approved' THEN NOW() ELSE auto_approved_at END,
    updated_at = NOW()
WHERE id = $1
RETURNING id, campaign_id, clipper_id, post_url, platform, platform_post_id, status, rejection_reason, approved_at, auto_approved_at, created_at, updated_at
`

type UpdateSubmissionStatusParams struct {
	ID              pgtype.UUID `json:"id"`
	Status          string      `json:"status"`
	RejectionReason pgtype.Text `json:"rejection_reason"`
}

func (q *Queries) UpdateSubmissionStatus(ctx context.Context, arg UpdateSubmissionStatusParams) (Submission, error) {
	row := q.db.QueryRow(ctx, updateSubmissionStatus, arg.ID, arg.Status, arg.RejectionReason)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.ClipperID,
		&i.PostUrl,
		&i.Platform,
		&i.PlatformPostID,
		&i.Status,
		&i.RejectionReason,
		&i.ApprovedAt,
		&i.AutoApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET display_name = COALESCE($2, display_name),
    email = COALESCE($3, email),
    updated_at = NOW()
WHERE id = $1
RETURNING id, email, display_name, role, created_at, updated_at
`

type UpdateUserParams struct {
	ID          string      `json:"id"`
	DisplayName pgtype.Text `json:"display_name"`
	Email       string      `json:"email"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.ID, arg.DisplayName, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserRole = `-- name: UpdateUserRole :one
UPDATE users
SET role = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, email, display_name, role, created_at, updated_at
`

type UpdateUserRoleParams struct {
	ID   string `json:"id"`
	Role string `json:"role"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserRole, arg.ID, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
