// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateCampaign(ctx context.Context, arg CreateCampaignParams) (Campaign, error)
	CreateSocialAccount(ctx context.Context, arg CreateSocialAccountParams) (SocialAccount, error)
	CreateSubmission(ctx context.Context, arg CreateSubmissionParams) (Submission, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteSocialAccount(ctx context.Context, arg DeleteSocialAccountParams) error
	GetCampaignByID(ctx context.Context, id pgtype.UUID) (Campaign, error)
	GetSubmissionByID(ctx context.Context, id pgtype.UUID) (Submission, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	ListActiveCampaigns(ctx context.Context) ([]Campaign, error)
	ListSocialAccountsByUserID(ctx context.Context, userID string) ([]SocialAccount, error)
	ListSubmissionsByCampaign(ctx context.Context, campaignID pgtype.UUID) ([]Submission, error)
	ListSubmissionsByClipper(ctx context.Context, clipperID string) ([]Submission, error)
	UpdateCampaignBudget(ctx context.Context, arg UpdateCampaignBudgetParams) (Campaign, error)
	UpdateCampaignStatus(ctx context.Context, arg UpdateCampaignStatusParams) (Campaign, error)
	UpdateSubmissionStatus(ctx context.Context, arg UpdateSubmissionStatusParams) (Submission, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error)
}

var _ Querier = (*Queries)(nil)
